README.md, ols-vms.conf, scripts/install-nodejs6
This should be enough to run the tests in a container on ols jenkaas to detect regressions.
=> Add a container definition for jenkaas support.

cmrh.conf.js, src/common/containers/container.css, src/common/containers/home.js, src/common/routes.js
Added simple home container (to render components in).
Also fixed configuration of CSS modules require hook.
=> Added simple home container

.simplecov, Makefile, build-exclude.txt, charm/charm-deps, charm/config.yaml, charm/dependencies-devel.txt, charm/layer.yaml, charm/metadata.yaml, charm/reactive/snap-build.py, charm/templates/snap-build_systemd.j2, ols-vms.conf, package.json, scripts/build.sh
This is based almost entirely on the charm in javan-rhino, with minor
tweaks.  build.snapcraft.io makes a terrible charm name, so (pending
bikeshedding) I've gone for "snap-build" by analogy with a few other OLS
snap-* services.
memcached is included even though we aren't using it yet, since it seems
probable we'll find some use for it.
=> Add a juju charm

charm/charm-deps, charm/layer.yaml, charm/reactive/snap-build.py
We need this following the layer-ols split.
=> Add layer-ols-http and adjust imports

src/common/components/button/button.css, src/common/components/button/index.js, src/common/components/forms/form.js, src/common/components/forms/index.js, src/common/components/forms/inputField.css, src/common/components/forms/inputField.js, src/common/components/forms/message.css, src/common/components/forms/message.js, src/common/components/hello-world.js, src/common/components/repository-input/index.js, src/common/containers/container.css
Using form components from MU.
Empty form:
On error:
On success:
=> Reusing MU form components in GH repository component

package.json, src/server/handlers/github.js
- Changed HTTP proxy setting to respond to http_proxy as well as
HTTP_PROXY
=> 13: Webhook endpoints (part 1.5)

environments/production.env, environments/staging.env
We'll still need secrets, but we might as well configure the non-secret
parts here.
=> Add staging/production GitHub configuration

src/server/handlers/github.js, src/server/handlers/launchpad.js, src/server/helpers/github.js, test/routes/src/server/routes/t_launchpad.js
We can only install a webhook if we have admin permissions, and in
general we only want to allow users to manipulate their own repositories
anyway.
=> Check for admin permissions on repository

src/common/components/build-history/index.js, src/common/components/spinner/index.js, src/common/components/spinner/spinner.css, src/common/components/spinner/spinner.svg, src/common/containers/builds.js, src/common/containers/container.css, src/common/reducers/snap-builds.js, test/unit/src/common/reducers/t_snap-builds.js
Builds list view is now auto fetching builds list every 5sec to keep builds status up to date.
=> Autorefresh builds list

src/server/handlers/webhook.js
It should go to the error log, and most of it should be at info rather
than debug.
=> Make webhook logging a little more useful

src/server/dev-server.js
=> Fix dev images URL

docs/routes.md, mocks/service/github/index.js, mocks/service/index.js, src/server/handlers/github-auth.js, src/server/handlers/github.js, src/server/routes/github.js, test/routes/src/server/routes/t_github.js
Simple internal API route for authenticated requests to get list of user GitHub repositories.
=> Repository listing api

src/common/components/header/index.js, src/common/containers/app.js, src/common/reducers/auth.js, src/server/handlers/github-auth.js, src/server/routes/github-auth.js, test/unit/src/server/handlers/t_github-auth.js
Updated logo to 'snapcraft', removed snapcraft.io link, added Login/Logout link (and proper logout handler that clears the session).
=> Header updates

src/common/actions/snaps.js, src/common/reducers/index.js, src/common/reducers/snaps.js, test/unit/src/common/actions/t_snaps.js, test/unit/src/common/reducers/t_snaps.js
Not used anywhere yet, but these actions allow to fetch user snaps from API.
=> Redux actions/reducer to store snaps (enabled repositories)

src/server/helpers/html.js
10:52 AM <beowulf> kfenn: do you want the font loaded from a cdn or locally?
10:53 AM <@kfenn> beowulf: What's the easiest?
10:53 AM <beowulf> kfenn: they're both trivial
10:53 AM <@kfenn> beowulf: Let's go with a CDN.
=> add ubuntu font from cdn

src/common/components/header/index.js, src/common/components/vanilla/heading/heading-one.css, src/common/components/vanilla/heading/heading-one.js, src/common/components/vanilla/heading/index.js, src/common/containers/container.css, src/common/containers/landing.css, src/common/containers/landing.js, src/common/style/base.css
Basic styles for landing page top banner (with placeholder images).
=> Landing page top banner

src/common/components/vanilla/list/icon-tick-grey.svg, src/common/components/vanilla/list/index.js, src/common/components/vanilla/list/list-divided-state.css, src/common/components/vanilla/list/list-divided-state.js, src/common/components/vanilla/list/list-divided.css, src/common/components/vanilla/list/list-divided.js, src/common/containers/landing.css, src/common/containers/landing.js
=> Added styles for features list on landing page

src/common/actions/auth-store.js, src/common/components/header/index.js, src/common/reducers/auth-store.js, test/helpers.js, test/unit/src/common/actions/t_auth-store.js, test/unit/src/common/reducers/t_auth-store.js
=> Clear macaroon from local storage when signing out

src/common/components/repositories-home/index.js, src/common/components/repositories-list/index.js, src/common/components/repository-row/index.js
No styling, date or anything yet.
Just simple link to build details page with status message.
=> Showing latest build status in enabled repos

src/common/components/build-row/index.js, src/common/components/build-status/buildStatus.css, src/common/components/build-status/index.js, src/common/components/repository-row/index.js, src/common/helpers/snap-builds.js, test/unit/src/common/helpers/t_snap-builds.js
Showing styles latest build with build date in repository listing.
=> Latest build status component

src/common/containers/landing.css, src/common/containers/landing.js, src/common/images/banner-WIP.svg, src/common/images/index.js
Final image and sizing is yet to be defined, so it's just to have something in place already.
=> Added landing page banner WIP image

README.md
- Update the README to include accurate local development instructions, including how to connect to GitHub itself.
QA
==
View [the README on my branch](https://github.com/nottrobin/build.snapcraft.io/blob/readme-linting-updates/README.md), check it reads okay.
=> Expand local development instructions

src/common/actions/create-snap.js, src/common/actions/register-name.js, src/common/helpers/api.js, src/common/reducers/register-name.js, test/unit/src/common/actions/t_register-name.js, test/unit/src/common/reducers/t_register-name.js
These aren't hooked up to anything yet.
=> Add actions for snap name registration

src/common/containers/landing.js
This text informally reviewed by Jamie Young.
=> Tweaks snap explanation text to better explain the Snap Store

npm-shrinkwrap.json, package.json, src/common/components/traffic-lights/index.js, src/common/components/traffic-lights/traffic-light.css, src/common/components/traffic-lights/white-tick.svg, src/common/containers/dashboard.js, test/unit/src/common/components/traffic-lights/t_traffic_lights.js
A component to show the user their progress through a set of milestones, with each milestone having 3 possible states (light a traffic light, "stop, get ready, go").
=> add traffic lights for user workflow

src/common/containers/dashboard.js, src/common/containers/select-repositories.js
add traffic lights to select-repository view, and update state on same and also dashboard
=> initial integration of traffic lights

src/common/components/vanilla/button/button.css, src/common/components/vanilla/button/index.js, src/common/containers/landing.js
Add the octocat icon to relevant landing page buttons
=> add icon to anchor button

src/common/components/header/index.js
Also changes 'Log in' to 'Sign in' and 'Log out' to 'Sign out' per spec.
=> Removes GitHub profile link from the header

src/common/components/repositories-home/index.js
=> Fix "Add repos" link

src/common/components/header/header.css, src/common/components/header/index.js
=> add snapcraft wordmark to header

src/common/components/user-avatar/index.js, src/common/components/user-avatar/user-avatar.css, src/common/containers/dashboard.js
github user name, name and avatar component
=> add user avatar component

src/common/components/first-time-heading/firstTimeHeading.css, src/common/components/first-time-heading/index.js, src/common/components/repositories-home/index.js, src/common/components/select-repositories-page/index.js, src/common/components/vanilla/button/index.js, src/common/containers/dashboard.js, src/common/containers/select-repositories.js
Currently relying on `store_name` and `snapcraft_data` in snaps response which is not fully supported yet, so the states may not be properly detected, but UI is done.
=> Contextual header

src/common/components/vanilla/button/button.css, src/common/components/vanilla/button/index.js, src/common/components/vanilla/heading/heading.css, src/common/containers/container.css, src/common/containers/landing.css, src/common/containers/landing.js
* many visual updates to the landing page per designer instructions
* see the buttons are larger
* see there is a h6 heading before the OS logos
* see that the bullet points is on a grey background strip
* see that the illustration is latest and on a white background
=> Landing page updates

src/common/containers/landing.css, src/common/containers/landing.js
* added dotted lines between elements on the workflow section
* removed bottom border on checkbuttons
1. go to the landing page
2. notice there is no bottom border on the light strip
3. notice there are dotted lines on the workflow area
=> adding dotted lines between workflow on landing page

src/common/components/user-avatar/index.js
Explicitly return null, not something falsey
=> return null in <UserAvatar /> render if { auth: authorisation } is falsey

src/common/components/repository-row/index.js, src/common/components/repository-row/repositoryRow.css
As per spec: we show a checkmark and the name in the table column if the
name is registered, and after successful registration we show a
checkmark and "Registered successfully" for two seconds before closing
the dropdown panel.
=> Show feedback on successful snap name registration

src/common/containers/landing.css, src/common/containers/landing.js, src/common/style/base.css, src/common/style/variables.js
* made the buttons green
* made the links blue
* replaced the external icon with a blue one
* replaced the workflow html with an svg
1. go to the landing page and confirm the changes
=> Landing page tweaks

environments/production.env, environments/staging.env
We're close enough to being ready for more widespread use that I think
now is a good time.
=> Remove team restrictions

src/server/handlers/launchpad.js, test/routes/src/server/routes/t_github.js, test/routes/src/server/routes/t_webhook.js
Fetching snapcraft.yaml from all 3 possible locations (`/snap/snapcraft.yaml`, `snapcraft.yaml`, `.snapcraft.yaml`) one by one.
If one succeeds we return it and don't fetch the others.
=> Fetching snapcraft.yaml from all 3 possible locations

mocks/service/github/index.js, mocks/service/github/responses.js, src/common/components/first-time-heading/index.js, src/common/components/repositories-home/index.js, src/common/components/repositories-home/repositories-home.css, src/common/components/select-repository-list/index.js, src/common/components/select-repository-list/styles.css, src/common/components/traffic-lights/traffic-light.css, src/common/components/user-avatar/index.js, src/common/components/user-avatar/user-avatar.css
- Changed default traffic light colour
- Demoted a heading to make it smaller
- Repositioned repository list heading next to button
- Changed the avatar from a square to a circle
- Changed colour of "login" heading to dark grey
- Re-aligned "Add" button to the right on the "select repos" list
- Added cancel button to select repos list
=> 203: UI fixes

src/common/containers/landing.js
* updated the workflow svg on the landing page
1. go to the landing page
2. see the workflow image is now https://assets.ubuntu.com/v1/84ce5b81-workflow_text-to-path02.svg
=> update to text on top workflow svg

src/common/components/repository-row/index.js
State of repository row component (state of open dropdowns) is now stored in browser storage, so when user navigates to SSO and returns back it's preserved.
Stored state is cleared when component is unmounted (for example when user navigates within the app itself).
=> Saving repository row state in browser store

docs/routes.md, src/common/actions/snap-builds.js, src/common/containers/build-details.js, src/common/containers/builds.js, src/common/reducers/snap-builds.js, test/unit/src/common/actions/t_snap-builds.js, test/unit/src/common/reducers/t_snap-builds.js
=> Show snap name in install help box

src/common/actions/register-name.js, src/server/handlers/launchpad.js, src/server/handlers/store.js, test/routes/src/server/routes/t_store.js
- Changed name registration endpoint to invalidate cache whenever name
is registered
- Changed name registration action creator to supply repository URL when
name is registered
=> 242: Snap data cache invalidation

src/common/actions/repositories.js, src/common/actions/snaps.js, src/common/components/page-links/index.js, src/common/components/select-repository-list/index.js, src/common/reducers/repositories.js, test/unit/src/common/actions/t_repositories.js, test/unit/src/common/reducers/t_repositories.js
* hide pagination component if there is only 1 page
* render pagination once and reuse
* rationalise state a little
=> Hide pagination on single page list

src/common/containers/landing.js
Small text change to landing page.
=> Text change: "Snapcraft" to "snaps"

src/common/components/select-repository-list/index.js, src/common/components/select-repository-row/index.js, src/common/components/select-repository-row/selectRepositoryRow.css, test/unit/src/common/components/select-repository-list/t_select-repository-list.js, test/unit/src/common/components/select-repository-row/t_select-repository-row.js
Enabled repos should be dimmed, inputs checked and disabled.
=> Filter out enabled repos

src/common/components/repository-row/index.js, src/common/components/repository-row/repositoryRow.css
Text-indent was causing the container to overflow the window.
=> replace remove anchor and text with span only

src/server/handlers/launchpad.js, test/routes/src/server/routes/t_launchpad.js
We cache Entry instances fetched from Launchpad in memcached, which
involves serialising them to a JSON representation.  On the way back
out, we need to turn them back into Entry instances, otherwise their
extra methods (`lp_save` and `lp_delete`) will be missing.
=> Re-wrap Entry instances returned by memcached

src/common/components/build-status/buildStatus.css, src/common/components/build-status/index.js, src/common/components/repository-row/index.js, src/common/helpers/snap-builds.js, test/unit/src/common/helpers/t_snap-builds.js
- Replaced status prop with a colour prop
- Added extra "Never built" build status for unconfigured repos
=> 237: Build status for unbuilt repository

src/server/handlers/launchpad.js, src/server/handlers/webhook.js, test/routes/src/server/routes/t_launchpad.js, test/routes/src/server/routes/t_webhook.js
BSI mainly uses the `auto_build` flag on a snap in Launchpad as a signal
to the webhook handler that it should dispatch builds.  However, it's
also piggy-backing on a Launchpad feature that dispatches builds for
"stale" snaps: the exact details of this are mostly not relevant for
BSI, but one relevant point is that a new snap is considered stale until
the first time `requestAutoBuilds` is called on it.  Setting
`auto_build` on a new snap therefore risks the dispatch of duplicate
builds depending on the exact timings involved.
We now set `auto_build` only when the snap has a `snapcraft.yaml` and
its name is registered, and we do so immediately after calling
`requestAutoBuilds` so that duplicate builds won't happen.
Fixes #225.
=> Only set auto_build once a snap is fully set up

src/common/components/header/header.css, src/common/components/header/index.js, src/common/components/user-avatar/index.js, src/common/components/user-avatar/user-avatar.css, src/common/containers/app.js, src/common/reducers/user.js, test/unit/src/common/components/header/t_header.js, test/unit/src/common/components/user-avatar/t_user-avatar.js, test/unit/src/common/reducers/t_user.js
Showing GH login when full user name is not available.
=> Handling empty GH user name

src/common/components/help/install-snap/index.js
=> Open snapd installation instructions in new tab

src/server/handlers/github-auth.js, src/server/handlers/github.js, src/server/handlers/launchpad.js, src/server/handlers/store.js, src/server/handlers/webhook.js, src/server/helpers/memcached.js
`internalGetSnapcraftYaml` and anything that uses memcached particularly
benefit, but in general most things end up being more straightforward
and less deeply-indented.
=> Convert server-side handlers to async/await

src/common/actions/auth-store.js
This is mostly a fairly literal translation, though I took the
opportunity to make the structure of `setShortNamespace` less
spaghetti-shaped.
=> Convert auth-store actions to async/await

charm/config.yaml, charm/reactive/snap-build.py
Fix a couple of bugs discovered while trying to roll out the latest code to staging.
=> Charm fixes

src/common/components/first-time-heading/index.js
* updated message to ‘Great! Next, register a snap name for publishing.’ based on [copy doc](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#)
1. first time setup
2. select a repo
3. see message
Fixes #307
=> updated first time message per spec

npm-shrinkwrap.json, package.json, src/common/components/repositories-list/index.js, src/common/components/repository-row/index.js, src/common/selectors/index.js, test/unit/src/common/selectors/t_selectors.js
See http://redux.js.org/docs/recipes/ComputingDerivedData.html
and https://github.com/reactjs/reselect
Then use that to determine if the first row in reposlist should be opened on register name.
=> computing derived data: use reselect to memoize 'hasNamedSnaps' selector

src/common/actions/register-name.js, src/common/components/repository-row/dropdowns/dropdowns.css, src/common/components/repository-row/dropdowns/index.js, src/common/components/repository-row/dropdowns/register-name-dropdown.js, src/common/components/repository-row/dropdowns/unregistered-dropdown.js, src/common/components/repository-row/icons/icons.css, src/common/components/repository-row/index.js, src/common/reducers/register-name.js, test/unit/src/common/actions/t_register-name.js, test/unit/src/common/reducers/t_register-name.js
=> Change registered name UI

test/unit/src/server/helpers/t_config.js, test/unit/src/server/metrics/t_github-users.js
Fix a couple of bugs that caused tests to fail on second and subsequent runs under `--watch`.
=> Fix tests under --watch

src/common/components/first-time-heading/index.js, src/common/components/repositories-home/index.js, src/common/selectors/index.js, test/unit/src/common/selectors/t_selectors.js
=> Fixes #303 - further first time steps shouldn't show when adding new repo

src/common/components/traffic-lights/index.js, src/common/components/traffic-lights/traffic-light.css
* removed the blue colour
* made the dots smaller
* removed the 1,2,3 label … can be removed if we like this better
* other design tweaks
1. go to the initial repo enrollment and check if the traffic lights match the design in the related issue
Fixes #354
=> refine look of traffic lights

charm/charm-deps
Consolidated changelog:
layer-apt:
Cope with unexpected null values in application config
layer-ols-pg:
Fix "ols-og" typo
layer-promreg-client:
Strip trailing newlines from promreg_authtoken
=> Apply various trivial charm layer fixes

src/common/components/traffic-lights/index.js, src/common/components/traffic-lights/traffic-light.css
and fix flow of elements in absence of label
=> Fix traffic light proptype validation warning

src/common/components/repositories-home/index.js
- Migrated remaining dispatch reference to mapDispatchToProps function
=> 489: Bugfix: "dispatch" is undefined on dashboard

src/common/components/repository-row/index.js
- Added feature to close name mismatch dropdown if name updates and is
fixed
- Fixes #397
=> 397: Fix name resolution bug

src/common/components/repositories-list/index.js, src/common/components/repository-row/index.js, src/common/selectors/index.js, test/unit/src/common/components/repositories-list/t_repositories-list.js, test/unit/src/common/components/repository-row/t_repository-row.js
<s>This is blocked because presently the user can never get in this state as they cannot register a name for a repo with no snapcraft.yaml?</s>
=> unconfigured dropdown first-time user flow

src/common/components/first-time-heading/index.js, src/common/components/traffic-lights/traffic-light.css
Fix #317 #499 #500
Made traffic lights take whole width, fixed issues with polling and connectors widths.
=> Updated traffic lights width and various fixes around it

src/common/components/repository-row/dropdowns/edit-config-dropdown.js, src/common/components/repository-row/dropdowns/index.js, src/common/components/repository-row/index.js, test/unit/src/common/components/repository-row/t_repository-row.js
- Added new repository row dropdown for editing snapcraft.yml
- Changed unconfigured dropdown to only display if snapcraft.yml doesn't
exist
=> 338: Edit snapcraft.yml feature

package.json
Works around yannickcr/eslint-plugin-react#1117.
=> Pin eslint-plugin-react to <6.10.1

src/common/components/repository-row/dropdowns/register-name-dropdown.js
See https://github.com/canonical-ols/build.snapcraft.io/pull/477#discussion_r105909345
=> space inline elements per review comment in #477

src/common/components/repository-row/index.js, src/common/helpers/api.js, src/server/helpers/memcached.js, test/helpers.js, test/unit/src/common/actions/t_create-snap.js, test/unit/src/common/actions/t_register-name.js
This covers the last few unit tests, as well as various odds and ends of
code elsewhere.
=> Convert remaining code to async/await

charm/charm-deps
The new layer-ols-http requires this.
=> Add interface-prometheus charm dependency

src/common/components/repository-row/dropdowns/register-name-dropdown.js, src/common/components/repository-row/index.js
Fixes #325
Added proper form with onSubmit callback to support sending name for registering with Enter key.
=> Register or change name with Enter key

environments/production.env, src/common/components/repositories-list/index.js, src/common/middleware/index.js, src/common/root.js, src/common/store/configureStore.js, src/server/helpers/html.js
Add Google Tag Manager. Tracking is controlled/configured in Google Tag Manager and Marketo.
Fixes #292
=> Add google tag manager

src/common/components/select-repository-list/index.js, test/unit/src/common/components/select-repository-list/t_select-repository-list.js
=> Disable Add button when no repos are selected

src/common/containers/build-details.js
=> More detailed build debug instructions

src/common/components/header/header.css, src/common/components/header/index.js
=> Beta flag in header logo

src/common/components/beta-notification/trigger.js
=> Beta nofication delay should be 2 minutes

src/common/components/select-repository-list/index.js
=> Fix pageSlice failing when there are no pageLinks

src/common/components/select-repository-list/index.js, src/common/components/select-repository-row/index.js, src/common/selectors/index.js, src/server/handlers/schema.js, test/unit/src/common/actions/t_repositories.js, test/unit/src/common/actions/t_snaps.js
Reimplements #572
Whitelisting and camelCasing props from GitHub API as part of normalizing.
Part of #541
=> Whitelist and camelCase props from GH API

test/unit/src/common/components/select-repository-list/t_select-repository-list.js
Tests barfing due to bad edit of test file.
=> Fix pare error in tests

src/common/actions/repository.js, src/common/components/select-repository-list/index.js, src/common/reducers/entities.js, src/common/selectors/index.js, src/server/handlers/github.js, test/unit/src/common/actions/t_repositories.js
Reimplements #571 
Updating add repository action names. 
Took a chance and did some repository/repo renaming on the way.
Part of #541
=> Updated action names for adding repo

src/common/actions/auth-store.js, src/common/helpers/macaroons.js, src/server/handlers/store.js, test/unit/src/common/actions/t_auth-store.js, test/unit/src/common/helpers/t_macaroons.js
This should help to debug #527.
=> Log information for register-name 401 failures

src/common/reducers/snaps.js, src/common/selectors/index.js, src/server/handlers/schema.js, src/server/routes/launchpad.js, test/routes/src/server/routes/t_launchpad.js, test/unit/src/common/reducers/t_snaps.js
- Added support for normalised store to FETCH_SNAPS_SUCCESS and
REMOVE_SNAP_SUCCESS
=> Refactor-redux: CALL_API

src/common/actions/repositories.js, test/unit/src/common/actions/t_repositories.js
- Added pageLinks to action payload
- Improved unit tests with stub data better reflecting a real API
response
=> 612: Fix select repositories page pagination

src/server/handlers/subscribe.js
=> Make MailChimp request through a proxy

src/common/reducers/index.js
Seems it got lost in some refactoring merges/conflicts.
=> Added back banner notification reducer

src/common/actions/repositories.js, src/common/reducers/repositories.js, src/server/handlers/github.js, src/server/routes/github.js, test/routes/src/server/routes/t_github.js, test/unit/src/common/actions/t_repositories.js, test/unit/src/common/reducers/t_repositories.js
- Replaced fetch repositories API calls with call-api middleware
=> 614: Refactor repositories API calls

src/common/actions/snap-builds.js, src/common/components/repositories-home/index.js, src/common/components/repositories-list/index.js, src/common/components/repository-row/dropdowns/name-mismatch-dropdown.js, src/common/components/repository-row/dropdowns/unconfigured-dropdown.js, src/common/components/repository-row/index.js, src/common/components/select-repositories-page/index.js, src/common/containers/build-details.js, src/common/containers/builds.js, src/common/containers/with-snap-builds.js, src/common/reducers/entities/snap.js, src/common/selectors/index.js, src/server/handlers/launchpad.js, src/server/handlers/schema.js, test/routes/src/server/routes/t_launchpad.js, test/unit/src/common/actions/t_snap-builds.js, test/unit/src/common/components/repositories-list/t_repositories-list.js, test/unit/src/common/components/repository-row/t_repository-row.js, test/unit/src/common/reducers/entities/t_snap.js, test/unit/src/common/reducers/t_snap-builds.js, test/unit/src/common/reducers/t_snaps.js, test/unit/src/common/selectors/t_selectors.js
Part of #465 
Normalizing responses that contain snap data, whitelist only needed props and make them camelCase.
=> Normalize snap responses

src/common/components/build-status/buildStatus.css, src/common/components/repositories-list/index.js, src/common/components/repositories-list/repositoriesList.css, src/common/components/repository-row/icons/icons.css, src/common/components/repository-row/icons/index.js, src/common/components/repository-row/index.js, src/common/components/vanilla/table-interactive/data-link.js, src/common/components/vanilla/table-interactive/index.js, src/common/components/vanilla/table-interactive/table.css, src/common/style/base.css, src/common/style/variables.js, test/unit/src/common/components/repository-row/t_repository-row.js
Fixes #321
See there for [visual spec](https://github.com/canonical-ols/build.snapcraft.io/issues/321#issuecomment-293893096).
=> Updated visual style of My Repos table

src/server/handlers/github-auth.js, test/routes/src/server/routes/t_github-auth.js
Part of #680
To give user some detail help text we need details on their organisations.
This PR adds user orgs list to user object in session (and redux store).
=> Add list of orgs to user info

src/common/components/build-row/index.js, src/common/components/build-status/buildStatus.css, src/common/components/repositories-home/index.js, src/common/helpers/snap-builds.js, test/unit/src/common/components/repositories-home/t_repositories-home.js
=> Fixes for build status not updating correctly on my repos page

src/common/components/repository-row/dropdowns/dropdowns.css, src/common/components/repository-row/dropdowns/register-name-dropdown.js, src/common/components/repository-row/dropdowns/remove-repo-dropdown.js, src/common/components/vanilla/button/button.css, src/common/components/vanilla/button/index.js, test/unit/src/common/components/repository-row/dropdowns/t_remove-repo-dropdown.js
Part of #686
As discussed there in comments we focus on updating button style only here, leaving layout updates to be confirmed and implemented later.
=> Updated dropdown cancel button style

src/common/containers/landing.js
Updated workflow diagram to have embedded font (and optimized with SVGOMG).
Fixes #773
=> Workflow diagram with embeded fonts

src/common/components/select-repository-list/index.js, src/common/components/select-repository-row/index.js, src/common/components/select-repository-row/selectRepositoryRow.css, src/server/handlers/github.js, src/server/handlers/schema.js, test/routes/src/server/routes/t_github.js, test/unit/src/common/components/select-repository-list/t_select-repository-list.js
=> Show non-admin repos as disabled on the list

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
This creates templates for issues and pull requests, similar to those on the ubnutu.com development repo. Aim is to keep all our issue and PR tracking similar.
=> Updating GitHub issues pr templates

src/common/middleware/call-api.js, test/unit/src/common/middleware/t_call-api.js
CALL_API middleware now supports fourth action type (additionally to request, success and error) that will be dispatched when response takes long time to load.
This functionality is needed for #661 to allow showing the spinner after 2 seconds.
It's just an extension of current CALL_API redux middleware, but it's not yet used anywhere in the app, so there is not much QA to do apart from running tests (which travis does anyway).
Part of #661
=> Added new action to API middleware to be called on delayed responses

src/common/style/base.css
Added font smoothing (same as Vanilla) to base CSS.
- All fonts should be smooooooth ;)
=> Added font smoothing to base styles same as Vanilla framework

src/common/root.js
Fixes #976.
I can absolutely believe this is the wrong place to set up this handler. Guidance welcome.
=> Notify Google Analytics on history manipulation

README.md, charm/layer.yaml, charm/reactive/snap-build.py, npm-shrinkwrap.json, package.json, src/common/components/footer/index.js, src/common/components/help/help-install-snap.js
=> Update repository location

charm/reactive/snap-build.py
Re-wire the charm hooks to setup poller properly on leadership changes.
=> Fixing poller for leadership changes.

src/common/components/header/header.css, src/common/components/header/index.js
I think we're at a good point to drop the beta logo.
=> Drop the beta banner

README.md
Updated README with missing dependencies like node version and python-lauchpad
=> Add node version and launchpad dependency in README

.dockerignore, Dockerfile
Add Dockerfile to project
(Make sure your file `environments/dev.env` is already configured)
- Add new [github app](https://github.com/settings/applications/new) with callback url: http://0.0.0.0:8000/auth/verify
- Add in file `environments/dev.env` the line: `GITHUB_AUTH_REDIRECT_URL=http://0.0.0.0:8000/auth/verify`
- `./run build`
- `docker build --build-arg COMMIT_ID=test --tag crazyimage .`
- `docker run --rm --env-file environments/dev.env -p 8000:80 crazyimage`
- Sign in
If your docker's ip is different adapt the QA.
=> Add Dockerfile to project

src/common/containers/app.js
Maintenance message updated following email conversation.
=> Updated maintenance message.

src/common/containers/app.js
Fixes for maintenance message (typo fix)
=> Updates to maintenance message

src/common/components/repositories-home/index.js
If repository was not built initially when added (for any reason) we make sure when refreshing 'My repos' page to request builds for it.
- Add new repository (preferably without snapcraft.yaml)
- To avoid building it when name is registered, register name first (before adding snapcraft.yaml)
- Add valid snapcraft.yaml later (because of running dev env on localhost there will obviously be no webhook, so repo will not build)
- Wait for BSI to refresh the list or sign out/in again to refresh it
- It should be detected that repo was never built and build should be triggered
Fixes #1036
=> Make sure to request builds of repos that were never built

src/server/handlers/webhook.js, test/routes/src/server/routes/t_webhook.js
We noticed that the Launchpad build farm was being spammed by identical
builds of certain snaps.  On investigation, this turned out to be
because BSI's GitHub webhook handler doesn't check that the pushed
branch is the one that Launchpad is configured to build for this
repository, so dispatched builds even in the rather common case that the
push was to some other branch.  Checking the branch should mean that we
have more resources for builds that aren't redundant.
It's probably simplest to QA this once it's on staging, but once it's there that can be done by pushing to a test repository's default branch vs. some other random branch and making sure that only the former case causes builds to be dispatched.
=> Check the pushed ref in the GitHub webhook handler

package.json
The API change doesn't affect us.
=> Upgrade to sinon 7.0.0

README.md
To prevent redirecting you need `NODE_ENV=development` in your env file.
=> Update README.md to add NODE_ENV to dev.env

src/common/components/footer/index.js
I also removed a grammatically-incorrect comma.
=> Fix forum link in footer

src/server/handlers/launchpad.js
As discussed in https://github.com/canonical-websites/build.snapcraft.io/issues/1181#issuecomment-444050083 we now correctly load all the snaps (not just the first batch).
To be able to reproduce the original issue and check if it's fixed without the need to have ~80 repos configured small local code change is needed to reduce the API batch size in dev environment.
In [`src/server/handlers/launchpad.js`](https://github.com/canonical-websites/build.snapcraft.io/blob/master/src/server/handlers/launchpad.js#L384-L389) change `internalFindSnaps`  to add `size` parameter to "findByURLPrefixes" API call:
```js
const result = await lpClient.named_get('/+snaps', 'findByURLPrefixes', {
parameters: {
url_prefixes: remainingPrefixes,
owner: `/~${username}`
},
size: 5
});
```
Size should be smaller …
=> Load all snaps (when there is more than one batch)

src/server/handlers/webhook.js
=> Catch webhook db errors
