canonical-web-and-design/build.snapcraft.io

webpack/dev-config.js

WEBPACK_DEV_URL was returned as false resulting in invalid assets URLs.

Fixing reading WEBPACK_DEV_URL from config

---

charm/charm-deps

At the moment this charm fails to deploy because no database is
available.  Fortunately, revision 13 of layer-ols drops the database
requirement.

Update OLS charm layer

---

charm/reactive/snap-build.py
environments/development.env

Reload systemd configuration after rendering the unit file, as otherwise
systemd isn't guaranteed to do the right thing on restart.
Change the development listen ports to 8000/8001.  This makes it easier
to make the charm work on all environments (since staging and production
will use 8000).
Make the development server listen on 0.0.0.0, as otherwise it's
effectively impossible to deploy a test development server using juju.
It does mean you have to be a bit careful that you have a firewall in
the way if you're standing up a test service somewhere, but that was
surely the case for other reasons anyway.

Make development configuration charm-friendly

---

package.json
src/common/actions/repository-input.js
src/common/components/repository-input/index.js
src/common/containers/home.js
src/common/reducers/index.js
src/common/reducers/repository-input.js
test/unit/helpers.js
test/unit/setup.js
test/unit/src/common/actions/t_repository-input.js
test/unit/src/common/reducers/t_repository-input.js

- better styles / reuse form components from MU

GitHub repository input component

---

charm/reactive/snap-build.py

Without this, the configuration file keeps getting rewritten with
different contents when various hooks fire, causing many unnecessary
service restarts.

Sort memcache_hosts in systemd config

---

Makefile

This will delete devDeps from node_modules, reducing churn in staging and production branches and preventing shipping unused code in deployments.

mirroring commit from mu; don't ship production npm deps

---

charm/templates/snap-build_systemd.j2
docs/environment-variables.md
package.json
src/server/helpers/session.js
test/unit/src/server/helpers/t_session.js

We're likely to want to use memcached for other things, such as caching
the GitHub repository URL -> Launchpad snap URL lookup.  Rename some
environment variables to be less session-specific, and add a "session:"
prefix to session-related keys.

Make way for non-session users of memcached

---

src/common/style/variables.js

It seems that we used old colour palette.
Updated based on current state of:
https://design.ubuntu.com/brand/colour-palette
https://github.com/ubuntudesign/ubuntu-vanilla-theme
https://github.com/ubuntudesign/vanilla-framework

Updated colour palette

---

src/server/dev-server.js
src/server/index.js
webpack/webpack-dev-server.js

Since src/server/launchpad/resources.js needs this now, we need to make
sure that it's registered in server startup paths.

Register babel-polyfill in a couple more places

---

npm-shrinkwrap.json
package.json

babel-polyfill is needed at run-time, so it must be in dependencies and
shrinkwrapped.

Shrinkwrap babel-polyfill

---

docs/routes.md
src/server/server.js

They're mounted under /api, so adjust the documentation to talk about
/api/launchpad/snaps.

Make the launchpad routes visible

---

src/server/launchpad/uri.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/server/launchpad/t_client.js
test/unit/src/server/launchpad/t_resources.js
test/unit/src/server/launchpad/t_uri.js

The client in the Launchpad source tree uses /api/devel as its service
root because it's running on launchpad.net itself, and in that context
it's easier to use the webservice on https://launchpad.net/api/devel/
and not have to worry about cross-origin issues.
However, in our case we're running on a different domain and using
api.launchpad.net, and https://api.launchpad.net/api/devel/ seems to
have at least some of the same rules as https://launchpad.net/api/devel/
in that it requires a Referer header.  That's awkward and unnecessary
here.  Using just https://api.launchpad.net/devel/ is simpler and avoids
this requirement.

Drop /api from Launchpad service root

---

docs/environment-variables.md
scripts/create-launchpad-credentials
src/common/actions/repository-input.js
src/common/components/repository-input/index.js
src/common/reducers/repository-input.js
src/server/handlers/login.js
src/server/helpers/config.js
src/server/openid/extensions.js
src/server/openid/relyingparty.js
test/routes/src/server/routes/t_login.js
test/unit/setup.js
test/unit/src/common/actions/t_repository-input.js
test/unit/src/common/reducers/t_repository-input.js
test/unit/src/server/openid/t_extensions.js
test/unit/src/server/openid/t_relyingparty.js

If LP_API_USERNAME is set, then we now create a snap based on the given
GitHub repository rather than merely verifying it.  This uses the
/launchpad/snaps API to create the snap in Launchpad, then redirects
through OpenID to authorise uploads of it to the store, then redirects
to the builds page for that repository.
If LP_API_USERNAME is not set, then we behave as before and only verify
the repository.  This is partly because it's handy in development, and
partly because we still need the verify actions to support future plans.

Hook up snap creation in the frontend

---

src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js

Launchpad defaults to [amd64, i386], which is possibly not ideal for
snaps.  Let's go for [amd64, armhf] instead; we need this to be
user-selectable in the long run, but this will be better for demo
purposes.
In the process, I fixed some buggy use of nock in tests: the Launchpad
client passes parameters to POST requests using the request body, not
the query string.

Create snaps with more appropriate architectures

---

charm/reactive/snap-build.py

Without this, the service won't be restarted if a unit reboots for any
reason.

Enable systemd unit on installation

---

src/common/actions/repository-input.js
src/server/helpers/config.js
test/unit/src/common/actions/t_repository-input.js

Rather than hardcoding api.github.com in RepositoryInput, expose
GITHUB_API_ENDPOINT to the client (which is safe) and use that.

Use GITHUB_API_ENDPOINT in RepositoryInput

---

src/server/handlers/github-auth.js

This matches the way GitHub API requests are made.
I haven't figured out a sensible way to test this, but we aren't testing
the other proxy uses either, so perhaps we can leave that aside for now.

Make GitHub auth verify request through a proxy

---

environments/production.env
environments/staging.env

Otherwise OpenID discovery breaks and confuses us all.  This is a bit of
a hack, but it's the simplest way out of our current situation.

Avoid proxy for login.ubuntu.com

---

src/common/actions/snap-builds.js
src/common/containers/build-details.js
src/common/containers/builds.js
src/common/reducers/snap-builds.js
src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/actions/t_snap-builds.js
test/unit/src/common/reducers/t_snap-builds.js

Going to `/user/repo/builds/` now properly asks LP for snap for given repository and then for builds of this snap.
To test is locally you need to have LP_ env variables properly set up with your user name and auth tokens. Also you need to have a snap created from GH url in LP (for your user) to make it available for your app.

Getting snap builds from LP into views

---

src/server/handlers/launchpad.js
src/server/helpers/memcached.js
test/routes/src/server/routes/t_launchpad.js
test/routes/src/server/routes/t_webhook.js

If `MEMCACHED_HOST` is not configured launchpad handler will just pass through memcached calls without caching anything.
This allows to run dev server without running memcached server and test without stubbing memcached.

Making memcached optional (for development and tests)

---

src/server/handlers/launchpad.js

This can't land until https://code.launchpad.net/~cjwatson/launchpad/snap-export-store-channels/+merge/314116 is on production, but is otherwise trivial.

Tell Launchpad to release snaps to edge

---

src/common/actions/repository-input.js
src/common/actions/webhook.js
src/common/components/repository-input/index.js
src/common/containers/repository-setup.js
src/common/reducers/webhook.js
src/common/routes.js
test/unit/src/common/actions/t_repository-input.js
test/unit/src/common/actions/t_webhook.js
test/unit/src/common/reducers/t_webhook.js

We should only install a webhook on the repository once we have a snap
for it to operate on.  This also reduces rollback complexity in the case
where something goes wrong while creating the snap.
I added a new client-side /:account/:repo/setup route that deals with
setting up the repository (currently only installing the webhook) and
then redirects to /:account/:repo/builds.  This gives us somewhere we
can run repository setup code after emerging from SSO authorisation, and
seems a better idea than doing it directly on /:account/:repo/builds.

Create webhook after creating snap

---

src/common/actions/snap-builds.js
src/common/components/repository-input/index.js

For consistency, we should import isomorphic-fetch anywhere that we're
using fetch, and not where we aren't.

Import isomorphic-fetch consistently

---

docs/routes.md
src/common/actions/request-snap-builds.js
src/common/containers/repository-setup.js
src/common/reducers/index.js
src/common/reducers/request-snap-builds.js
src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/actions/t_request-snap-builds.js
test/unit/src/common/reducers/t_request-snap-builds.js

We can do this in parallel with installing the webhook, and it means
that we get a satisfying response from the builds page right away.

Request initial builds from repository setup page

---

package.json

Our Jenkins environment sets a proxy, and that shouldn't be used for
tests because it isn't going to be able to contact mock services.  This
was already done for the route tests, but now we have unit tests that
exercise some relevant code paths.

Unset proxy when running unit tests

---

src/common/actions/repository-input.js

As title says.
A little hacky (as it seems the only way to check this specific error is to compare error message), but seems to be working good enough.

If error from LP says that snap exists, just redirect to builds view

---

src/server/handlers/github.js
src/server/handlers/webhook.js
test/routes/src/server/routes/t_webhook.js

We pass the hex digest of an HMAC to GitHub for it to use as the secret
for a new HMAC; this is not equivalent to chaining multiple update calls
onto a single HMAC instance.  Fix the verification process to match what
GitHub is doing.

Fix HMAC chaining in webhook verification

---

src/common/components/build-row/index.js

duration and dateStarted may be null, so just leave the corresponding
cells empty in that case rather than having it come out as "a few
seconds" and "Invalid date" respectively.
While I'm here, render dates using ISO 8601 order in the dateStarted
tooltip.

Tidy up duration/date display on builds page

---

src/server/handlers/launchpad.js
src/server/helpers/memcached.js

If internalFindSnap doesn't find the given repository URL in memcached,
it looks for it in Launchpad, iterating through all snaps with that URL.
If one of them matches the service username, it stores that in memcached
and resolves the promise with its link; otherwise, it rejects the
promise with a snap-not-found error.
However, this code incorrectly fell through to the last-resort promise
rejection, and because memcached set is asynchronous the rejection would
typically be processed before the resolution.  We didn't catch this
because the memcached stub in tests was synchronous.  Avoid this
incorrect fallthrough and strengthen the tests to catch bugs of this
form.
Fixes #79.

Fix spurious promise rejection in internalFindSnap

---

npm-shrinkwrap.json
package.json
src/server/handlers/github.js
src/server/handlers/launchpad.js
src/server/handlers/webhook.js
src/server/logging/index.js
src/server/server.js

Right now, we only log to the console.  This is fine for development, but cumbersome for the staging/production deployments, where the only way to debug anything is to log into the unit and use `systemctl status --lines=1000 snap-build`; this is made worse by switch deploys, since the unit that contains the logging information is likely to go away.
Part of fixing this will be sending logs to ELK, which is outside the scope of this PR since it'll be done by the Mojo spec.  However, as a prerequisite for that, we need to log to files.  This PR arranges to write logs to files under `LOGS_PATH` (already set by the charm), and tries to reserve the `express-error` logger only for actual errors.

Various logging improvements

---

src/common/components/repository-input/index.js

Helps to finalise fixing issues around #46
Having input available before logging into GH may be bit confusing (as 'Create' button cannot be clicked). Also putting value into the input and logging to GH later makes the value disappear because of auth reload.
So it seems easier to simply disable whole Step 2 before user logs into GH in Step 1.

Disabling repository input if user is not logged to GH

---

src/common/actions/snap-builds.js
src/common/containers/builds.js
src/common/reducers/snap-builds.js
test/unit/src/common/actions/t_snap-builds.js
test/unit/src/common/reducers/t_snap-builds.js

Currently we fetch snap by repo URL every time we fetch builds (every 15s on builds page). It's unnecessarily doubles numbers of requests made from the client.
With this update snap link is saved to the store and only list of builds is being fetched every 15 seconds to keep it up to date.

Only fetch snap by repo URL when needed

---

src/common/containers/repository-setup.js

After introducing `withRepository` higher order component repository setup container stopped proceeding automatically.
It happened because `componentWillRecieveProps` was never called.
`WithRepository` higher order component re-renders wrapped component so `componentDidMount` needs to be used instead of `componentWillRecieveProps`.

Fix repository setup not proceeding automatically

---

mocks/service/index.js
npm-shrinkwrap.json
package.json
src/common/actions/create-snap.js
src/common/actions/repositories.js
src/common/actions/snap-builds.js
src/common/helpers/config.js
src/config/defaults.js
src/server/dev-server.js
src/server/handlers/login.js
src/server/handlers/universal.js
src/server/helpers/config.js
test/helpers.js
test/setup.js
test/unit/src/common/actions/t_create-snap.js
test/unit/src/server/handlers/t_login.js
test/unit/src/server/helpers/t_config.js
test/unit/src/server/openid/t_relyingparty.js
webpack/build-config.js
webpack/webpack-dev-server.js

- nconf removed due to unavoidable dependency on the Node fs API
- Rewritten config helper exposing an immutable config object
- Added "baked in" config to JS bundle, using WebPack.DefinePlugin to
replace process.env
- Added environment variables to Makefile
- Removed runtime config from HTML helper component

58: Refactor configuration

---

src/common/components/repository-row/index.js

can be either a react element (name not registered case) or a string (every other case)

fix proptype validation for repo-row error message

---

src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js

We don't need anything else, and this reduces risk in the event of a
macaroon leaking.

Restrict store macaroons to the edge channel

---

docs/routes.md
mocks/service/github/index.js
src/common/actions/repositories.js
src/common/components/page-links/index.js
src/common/components/page-links/styles.css
src/common/components/repositories-list/index.js
src/common/components/repositories-list/styles.css
src/common/reducers/repositories.js
src/server/handlers/github.js
src/server/routes/github.js
test/helpers.js
test/routes/src/server/routes/t_github.js
test/unit/src/common/actions/t_repositories.js
test/unit/src/common/components/page-links/t_page-links.js
test/unit/src/common/reducers/t_repositories.js

- New PageLinks component
- Added feature to fetchRepositories handler to transform and pass on
page links from GitHub API
- Split FETCH_REPOSITORIES_SUCCESS from SET_REPOSITORIES to clean up a
side-effect
- Repositories are now cleared from store when loading new pages
- New and updated unit tests

67: Repo pagination

---

src/server/handlers/launchpad.js
src/server/handlers/webhook.js
src/server/helpers/github.js
test/routes/src/server/routes/t_webhook.js

We want to move to creating the snap in Launchpad somewhat earlier,
before snapcraft.yaml necessarily exists.  As a prerequisite for this,
the webhook needs to check whether snapcraft.yaml exists before
dispatching builds.
The `auto_build` flag on snaps, previously unused in this workflow, is
now used to indicate whether the snap has been sufficiently set up for
builds to be dispatched.  This lets us minimise the number of GitHub
queries we make from the webhook, which is important since that doesn't
have user authorisation available to it.

Check snapcraft.yaml existence in webhook

---

src/common/containers/dashboard.js
src/common/containers/landing.js
src/common/routes.js
src/server/handlers/github-auth.js
test/routes/src/server/routes/t_github-auth.js

Added separate landing container.
With this PR:
- Repository listing is moved to new `/dashboard` route (URL will likely to be changed later).
- `build.snapcraft.io` renders landing container.
- When user signs in, GitHub redirects back to `/dashboard`.

Separating landing and dashboard routes and containers

---

src/common/actions/create-snap.js
src/common/actions/repositories.js
src/common/actions/snap-builds.js
src/common/helpers/api.js

`getError` and `checkStatus` have the same implementation for anything
that consumes internal APIs.

Refactor common API helper methods into one place

---

docs/routes.md
src/common/actions/create-snap.js
src/server/handlers/launchpad.js
src/server/handlers/webhook.js
src/server/routes/github.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/actions/t_create-snap.js

We'll soon need to move the process of getting a package_upload macaroon
to the client side, which means that the client will need to know the
snap name when it's creating a snap.  Add an
`/api/github/snapcraft-yaml/:owner/:name` route to fetch the parsed
file, and change `/api/launchpad/snaps` to take the snap name, series,
and channels as parameters; this lets us control more of the data flow
from the client side.

Initiate the snapcraft.yaml check from the client

---

docs/routes.md
mocks/service/launchpad/index.js
src/server/handlers/launchpad.js
src/server/routes/launchpad.js
test/routes/src/server/routes/t_launchpad.js

This isn't used yet, but it will be used by the new authz workflow to
send pre-authorized `package_upload` macaroons to Launchpad.

Add /api/launchpad/snaps/authorize route

---

src/common/actions/create-snap.js
src/common/components/select-repository-list/index.js
src/server/handlers/github-auth.js
test/routes/src/server/routes/t_github-auth.js
test/unit/src/common/actions/t_create-snap.js

- Added initial support for batched snap creation to createSnap action
creators
- Changed redirect on successful login to "select repositories"
dashboard view

100: Batched repository selection

---

src/common/actions/user.js
src/common/components/header/index.js
src/common/containers/app.js
src/common/reducers/index.js
src/common/reducers/user.js
src/server/handlers/github.js
src/server/routes/github.js
test/routes/src/server/routes/t_github.js
test/unit/src/common/actions/t_user.js
test/unit/src/common/reducers/t_user.js

API route and redux actions/reducer to fetch current user data from GH.
GH OAuth verify only sends token, not any other user info, so we need to fetch it from API.
It's not perfect when we do it from client side, because it means we know user is authenticated (from session) but still have to wait for user data API call.
I guess other option would be to do the API call on server side (in verify handler), and keep user data in session once we get it from GH (and only then redirect back to app, with user data injected into state).

Getting GitHub user info to the app

---

src/common/components/header/index.js

Declaring an object with a particular shape is done using
`PropTypes.shape`, not `PropTypes.object`.

Fix incorrect PropTypes in Header

---

webpack/dev-config.js

Doing this explicitly in the development config results in many fewer
errors in the browser console, which makes it easier to spot real
problems.

Explicitly inject NODE_ENV=development in webpack

---

src/common/actions/auth-store.js
src/common/reducers/auth-store.js
test/helpers.js
test/unit/src/common/actions/t_auth-store.js
test/unit/src/common/reducers/t_auth-store.js

We need to be able to check whether the user is already signed into the
store; the existing actions only arrange to set authStore.authenticated
on the first page load.  These new actions check local storage for
existing macaroons.
We should check the expires caveat on existing macaroons; this is
compounded by us not yet clearing local storage when the user signs out
(#125).  In the short term a workaround is to delete entries from
storage manually using devtools.

Add actions for checking store sign-in

---

src/common/actions/create-snap.js
src/common/components/select-repository-list/index.js
src/common/reducers/repositories-status.js
src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/actions/t_create-snap.js
test/unit/src/common/reducers/t_repositories-status.js

Creating snaps now requires being "signed into the store", which equates
to having a discharged package_upload_request macaroon in local storage.
For each snap to be created, we request a specific non-expiring
package_upload macaroon for it and tell the backend to store that in
Launchpad.  This allows batch-creation of snaps, and avoids a round-trip
through SSO per snap.
This leaves some unused endpoints around, but this PR is already large
enough; they can be cleaned up later.
The UI is pretty weak in places, but this should be enough to unblock other development (in particular, the `package_upload_request` macaroon can be reused for registering a snap name, after lifting up the `authStore` state to some suitable common ancestor component, and it should now be possible to put the rest of …

Use package_upload_request macaroons for authz

---

src/server/helpers/session.js

I got stuck in a sso loop, I've added a bug for part of it (can't see login/failed #133), but this I think fixes the loop bit (cookies not being set in http, therefore you are simply redirected to sso for all eternity) ... and now I've pushed I see why no-one else sees this, because they don't have `COOKIE_SECURE` in the env file _at all_ whereas I have it as `false`

allow setting secure cookies to false

---

webpack/build-config.js

We're now using ES6 generators on the client side, so we need this.

Add babel-polyfill to production bundle build

---

src/common/reducers/auth-error.js
test/unit/src/common/reducers/t_auth-error.js

Otherwise we get this when navigating directly to `/login/failed`
(though not when being sent there due to an error, since `handleMatch`
sets `authError` to an object in the initial state):
Warning: Failed prop type: Invalid prop `authError` of type `array`
supplied to `LoginFailed`, expected `object`.
in LoginFailed (created by Connect(LoginFailed))
in Connect(LoginFailed) (created by RouterContext)
in div (created by App)
in App (created by Connect(App))
in Connect(App) (created by RouterContext)
in RouterContext
in Provider (created by Html)

Make the authError state be consistently an object

---

src/common/components/footer/footer.css
src/common/containers/container.css
src/common/containers/landing.css
src/common/containers/landing.js

Also included bottom section about snap (and footer fixes):

Added brand, workflow and snap sections with placeholder images

---

src/server/helpers/html.js

https://trello.com/c/bLfTwK9x/138-landing-ubuntu-font-not-rendering-in-light-weight

Added Ubuntu Light support for headings

---

src/common/actions/snap-builds.js
src/common/components/build-history/index.js
src/common/containers/build-details.js
src/common/containers/builds.js
src/common/containers/repository-setup.js
src/common/reducers/snap-builds.js
test/unit/src/common/actions/t_snap-builds.js
test/unit/src/common/reducers/t_snap-builds.js

Not as elegant as I hoped, but this extends `snapBuilds` reducer to allow storing builds for many repositories (keyed by repo full name).
Updated relevant views (repository setup, builds list and build details).
Currently not connected to new dashboard.

Storing builds for multiple repositories in redux store

---

docs/routes.md
src/server/handlers/github.js
src/server/handlers/webhook.js
src/server/helpers/memcached.js
test/routes/src/server/routes/t_github.js
test/routes/src/server/routes/t_webhook.js

Positive responses are cached to avoid an unreasonable number of
requests, and the webhook clears the cache so that we notice changes
more quickly at least for enabled repositories.
I haven't tested this in a browser since this was mostly done in spare minutes at the hospital; somebody not on leave might want to give this a quick run to make sure it doesn't explode or anything.

Include snap name in /api/github/repos response

---

src/common/style/base.css

Vanilla, Ubuntu and snapcraft.io all have orange links.

Bring back orange non-underlined links

---

src/common/components/repositories-home/index.js
src/server/handlers/github-auth.js
test/routes/src/server/routes/t_github-auth.js

Login with GH should properly redirect to /dashboard and only if user doesn't have enabled repos show add repositories view (go to/dashboard/select-repositories).

Login redirect to dashboard

---

src/common/components/repositories-list/index.js
src/common/components/repositories-list/repositoriesList.css
src/common/components/repository-row/index.js
src/common/components/vanilla/table-interactive/dropdown.js
src/common/components/vanilla/table-interactive/index.js
src/common/components/vanilla/table-interactive/row.js
src/common/components/vanilla/table-interactive/table.css

Simple dropdown component for interactive table with basic usage in RepositoryRow.

Added table dropdown component with dummy usage in repository row

---

docs/routes.md
src/server/handlers/store.js
src/server/routes/index.js
src/server/routes/store.js
test/routes/src/server/routes/t_store.js

Simple endpoint to proxy register-name requests from the client in
advance of cross-origin support in the SCA register-name endpoint.

Add /api/store/register-name endpoint

---

src/common/components/repositories-home/index.js
src/common/components/select-repositories-page/index.js
src/common/components/select-repository-list/index.js

Text changes in the Dashboard:
- Removes spurious sign-in prompt from Add dialog
- Changes 'Enable repos' to 'Add'
- Removes incorrect statement about all your repos being added (will be replaced by the first-run flow later)
- Shortens button label 'Add new repository' to 'Add repos...'.

Text fixes

---

src/common/components/footer/index.js

Since, on this site, we don’t mention the platform that the footer was disclaiming.

Removes no-longer-needed text from the footer

---

src/common/components/footer/index.js

http://www.ubuntu.com/legal redirects to https://www.ubuntu.com/legal
anyway, so we might as well link to the latter directly.

Use https link for www.ubuntu.com

---

src/common/components/header/header.css
src/common/components/header/index.js

Still has the same font, but without the border, hover affect and with 'Hi,' text it should look less like a link.

Making user name in header not look like a link

---

src/common/components/repositories-list/index.js
src/common/components/repository-row/index.js
src/common/components/repository-row/repositoryRow.css
src/common/components/select-repository-list/index.js
src/common/components/vanilla/button/button.css
src/common/components/vanilla/button/index.js

Signing into the store is now done on the main dashboard page as part of
registering a name, and the store macaroon is used to register the name
over the API.
We don't yet do anything useful with the registered name; the next step
will be to push it into Launchpad and create builds immediately after
name registration is complete.

Add name registration to UI

---

src/common/reducers/snaps.js
test/unit/src/common/reducers/t_snaps.js

On the first time through for a new user, /dashboard will fetch snaps
and find an empty list, then send the user to
/dashboard/select-repositories.  If the user then creates a snap and
returns to /dashboard, the store may already have state that looks like
`{ snaps: { success: true, snaps: [] } }`, which will cause it to
immediately redirect back to /dashboard/select-repositories, entering a
redirect loop.
Clearing previous success/error state in response to the `FETCH_SNAPS`
action avoids this problem.

Fix dashboard redirect loop

---

src/common/components/help/install-snap/index.js
src/common/containers/build-details.js
src/common/containers/builds.js

Reflecting that (a) we’re building on only two architectures and (b) the build page doesn't yet know whether this build succeeded.

Tweaks snap install text

---

docs/routes.md
src/common/actions/auth-store.js
src/common/actions/create-snap.js
src/common/actions/register-name.js
src/common/components/repository-row/index.js
src/common/helpers/api.js
src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/actions/t_create-snap.js
test/unit/src/common/actions/t_register-name.js

Enabling a repository now creates a bare snap object in Launchpad with
no store configuration, and all the store configuration is filled in
later once the name is registered.  This lets us remove all dependencies
on being signed into the store from `/dashboard/select-repositories`.

Move snap authorization after name registration

---

src/common/actions/create-snap.js
test/unit/src/common/actions/t_create-snap.js

We used to create a webhook during the setup workflow, but that fell out
during the major reorganisations of the last couple of weeks.  This
restores it.  We can safely create the webhook as the very first thing
we do, since the webhook handler will fail cleanly if the snap doesn't
exist yet, and error handling is easier this way round.
This duplicates part of `src/common/actions/webhook.js`, but that can
just be removed after this is in place; we don't need to have separate
actions and state for this.

Create webhook before creating snap

---

src/common/actions/register-name.js
src/common/components/repository-row/index.js
test/unit/src/common/actions/t_register-name.js

Once snapcraft.yaml exists and the name is registered, we can trigger
builds.  One path for this (already implemented) is that if the name is
registered first then we may be told of a new snapcraft.yaml by way of a
webhook push event.  The other possibility is implemented here: if
snapcraft.yaml already exists when the name is registered, we should
trigger builds at that point.

Trigger builds if possible once name is registered

---

src/common/containers/landing.js

* replaced workflow image with a new svg with the ubuntu font as vectors
1. on the landing page, see that the workflow image font is ubuntu now
Fixes #212

replace workflow image with ubuntu font as vectors

---

src/common/components/vanilla/heading/index.js

With recent changes to headings they got `text-align: left` by default (if no other specified).
This has broken some headings already centered by styles from parent element.
By default heading should not specify alignment at all (so it would inherit text-align from parent).

Fix default heading align

---

src/common/components/select-repositories-page/index.js

Previously on select-repositories it was assumed that snaps and builds data will be available in the store already (from dashboard), but it turned out not to be true is some cases (like full page reloads).
So now we fetch all the data needed for first time heading in select-repositories too.
Should fix #195 and #214

Properly fetching data needed for first time heading

---

src/common/actions/auth-store.js
src/server/handlers/store.js
src/server/routes/store.js
test/routes/src/server/routes/t_store.js
test/unit/src/common/actions/t_auth-store.js

These will let us deal with signing the developer agreement and setting
the short namespace.
We now request the new `edit_account` macaroon permission along with
`package_upload_request`, so that we can use `PATCH /dev/api/account`.

Add proxy routes for store account management

---

src/common/components/forms/message.js
src/common/components/repositories-list/index.js
src/common/components/repository-row/index.js
src/common/components/repository-row/repositoryRow.css
src/common/components/select-repositories-page/index.js
src/common/components/vanilla/heading/index.js
src/common/containers/landing.js

Asking for review early, even though this doesn't cover all error states and keeping the dropdown open through SSO dance.
* We're not handling the case when the SSO session expires (or maybe the macaroon?) in the background, the user is left with no clear way of dealing with that (the button does not change to 'Sign in').
* Click "Not registered" in repos to build and publish list.
* Check register button is green and on RHS appropriately spaced.
* Check cancel button is plain text.
* Enter "-ubuntu" in text input, check error is "Sorry the name can't start or end with a hyphen."
* Enter "ubuntu-" ... check as above.
* Enter "ubuntu" in text input, check error is "Sorry, that name is already taken. Try a different name.
If you think you should have sole rights to the name, you can file a …

Snap name registration tidying

---

src/common/actions/auth-store.js
src/common/actions/register-name.js
src/common/components/repositories-list/index.js
src/common/components/repository-row/index.js
src/common/components/repository-row/repositoryRow.css
src/common/reducers/auth-store.js
src/server/handlers/login.js
src/server/handlers/universal.js
src/server/openid/relyingparty.js
test/unit/src/common/actions/t_auth-store.js
test/unit/src/common/actions/t_register-name.js
test/unit/src/common/reducers/t_auth-store.js

New store accounts may require some additional setup.  Prompt the user
to sign the developer agreement if necessary, and try to set their short
developer namespace to be the same as their SSO username.

Improve handling of new store accounts

---

src/common/actions/register-name.js
src/common/reducers/snaps.js
test/unit/src/common/actions/t_register-name.js
test/unit/src/common/reducers/t_snaps.js

Snaps with registered name should have `store_name` property set to a registered name (which is done on LP side)
Right now after registering the name from BSI we are not updating snaps list, so on client side they don't have this property set yet, so for example first time heading does not properly move to next step (because it sees snaps still as unregistered).
We could possibly reload snaps list (fetch them again) when name is registered, but this will be an unnecessary request and UI update.
In this PR I update the `store_name` directly in snaps data in redux store in response REGISTER_NAME_SUCCESS action.

Updating store_name in snap when name is registered

---

src/common/actions/snap-builds.js
src/server/handlers/launchpad.js
src/server/handlers/webhook.js
test/routes/src/server/routes/t_launchpad.js
test/routes/src/server/routes/t_webhook.js
test/unit/src/common/actions/t_snap-builds.js

Currently our find snap route returns just a `self_link` of a snap for given repository.
To get whose snap data we would need to call LP API again (even though we got all the snap data in first place).
This PR updates `GET /launchpad/snaps` (via `internalSnapFind`) to return whole snap object instead of just `self_link`.
This allows webhook to know if `auto_build` is set on snap without additional API request.
It will also allow us to show snap name in UI (install instructions) without additional API calls (this will be done in separate PR).

Fetch all snap info in one request

---

src/common/components/repository-row/index.js

This is per the specification, because "Configured" gets too monotonous
when there are many configured repositories.

Only show a checkmark for configured repos

---

src/common/components/repository-row/index.js
src/common/components/repository-row/repositoryRow.css

This puts the asset URL together with the rest of its presentation; and
this code layout works better when we need an icon with an action
associated with it, as we will for snap removals.
While I was at it, I made the asset URL use HTTPS rather than HTTP.

Tweak icon CSS to match MAAS Vanilla theme

---

docs/routes.md
src/common/actions/snaps.js
src/common/components/repositories-list/index.js
src/common/components/repository-row/index.js
src/common/components/repository-row/repositoryRow.css
src/common/components/vanilla/button/button.css
src/common/components/vanilla/button/index.js
src/common/reducers/snaps.js
src/server/handlers/launchpad.js
src/server/launchpad/client.js
src/server/launchpad/resources.js
src/server/routes/launchpad.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/actions/t_snaps.js
test/unit/src/common/reducers/t_snaps.js
test/unit/src/server/launchpad/t_client.js
test/unit/src/server/launchpad/t_resources.js

This removes the snap from Launchpad and invalidates relevant entries in
memcached.  It is per the specification except that it doesn't yet say
anything about published builds, and that the remove icon is always
shown rather than only being shown when hovering over a row.

Add snap removal support

---

src/common/components/repository-row/index.js

* added the 'snap/' to the filename 'snapcraft.yaml' to put the file in it's correct location
1. add a repo to build that doesn't have a snapcraft.yaml file
2. see that the instructions offer you a link that will let you create the file in the /snap directory [example](https://github.com/pmahnke/build.snapcraft.io/new/master?filename=snap%2Fsnapcraft.yaml&value=%0Aname%3A%20my-snap-name%20%23%20you%20probably%20want%20to%20%27snapcraft%20register%20%3Cname%3E%27%0Aversion%3A%20%270.1%27%20%23%20just%20for%20humans%2C%20typically%20%271.2%2Bgit%27%20or%20%271.3.2%27%0Asummary%3A%20Single-line%20elevator%20pitch%20for%20your%20amazing%20snap%20%23%2079%20char%20long%20summary%0Adescription%3A%20%7C%0A%20%20This%20is%20my-snap%27s%20description.%20You%20have%20a%20paragraph%20or%20two%20to%20 …

moving the snapcraft.yaml template to the /snap directory

---

src/common/actions/create-snap.js
src/common/actions/select-repositories-form.js
src/common/components/select-repository-list/index.js
src/common/reducers/repositories-status.js
src/common/reducers/select-repositories-form.js
test/unit/src/common/actions/t_create-snap.js
test/unit/src/common/actions/t_select-repositories-form.js
test/unit/src/common/reducers/t_repositories-status.js
test/unit/src/common/reducers/t_select-repositories-form.js

Clear out any previous state each time we mount the SelectRepositoryList
component, so that it doesn't get confused into believing that it just
finished adding repositories and redirect the user back to the
dashboard.
Fixes #204.

Fix "Add repos" loop after the first time through

---

src/common/components/vanilla/button/button.css
src/common/containers/landing.css
src/common/containers/landing.js

* lowered the font size on the h1 text (by making it an h2)
* reduced a lot of margins around the image and button to make it all tighter
1. go to the landing page (not logged in)
2. see the button above the fold

doing whatever it takes to get the green button above the ‘fold’

---

src/server/handlers/github.js
src/server/handlers/launchpad.js
src/server/handlers/store.js
src/server/handlers/webhook.js
src/server/helpers/memcached.js
test/routes/src/server/routes/t_launchpad.js

This is much easier to use, especially in conjunction with other code
using promises.  The test stubs already used promises, but this had a
dangerous gotcha: code that expected memcached methods to return
promises would work under test but fail in production, as was the case
with the webhook implementation.  Using promises everywhere avoids this
problem.
I considered using one of the existing memcached/promise integration
libraries, but all the ones I could find depended on some specific
promise library, and it's so easy to do by hand that it wasn't worth the
hassle.

Convert all uses of memcached to promises

---

docs/environment-variables.md
docs/memcached.md
src/common/containers/build-details.js
src/common/containers/builds.js
src/server/handlers/github.js
src/server/handlers/launchpad.js
src/server/handlers/store.js
src/server/handlers/webhook.js
src/server/helpers/memcached.js
test/routes/src/server/routes/t_launchpad.js
test/routes/src/server/routes/t_webhook.js

Launchpad sets the `store_name` for a snap once it's authorized.
So after a successful authorize call we need to clear all snap related caches to make sure they will be updated with fresh data about snap.

Clear snap cache when name registered

---

src/common/containers/build-details.js
src/common/containers/builds.js
src/common/containers/with-repository.js
src/common/containers/with-snap-builds.js

Both builds listing for repo and build details did a bunch of same fetch logic (getting repo from URL, fetching snap and builds for it), so I extracted this functionality to higher order component.

Extracted fetching snap builds to higher order component

---

src/common/components/repository-row/index.js

The actionText on the Register button should change from “Register” to “Register Name”

Change "Register" button text to "Register Name"

---

Makefile

We use Juju 2 in production, so we might as well make the `deploy`
target work with Juju 2 as well.

Adjust `make deploy` to work with Juju 2

---

charm/metadata.yaml

Allow the charm to have `db` and `db-admin` relations on the `pgsql`
interface.  These don't do anything yet, but having stubs in place lets
us move on to the next phase of a stepped rollout.

Add stub PostgreSQL relations

---

src/server/launchpad/client.js
src/server/launchpad/resources.js

This is a small proof-of-concept to see if people like this before I
start sending PRs to convert the whole codebase.  I find this style
easier to read and less error-prone, especially around error handling,
and it generally decreases indentation levels.
I'm deliberately not converting tests at the same time as the code under
test, to provide better assurance that I haven't applied a mistaken
conversion to both.

Convert internal LP client to async/await

---

test/routes/src/server/routes/t_login.js

Fix for #266
Login route tests were failing randomly on some dev environments.
It turned out it was issue with usage of `nock`.
Tests for authentication routes were mocking SSO requests, but these mock were also being created (and never called) for discharge macaroon routes. And for some reason it made nock go nuts sometimes.
This PR moves mocks into authentication context, so they are only created when they are needed.
Also added checks if all mocks are satisfied.

Fixes #266: Fixed mocked requests in login route tests

---

test/unit/src/server/launchpad/t_client.js
test/unit/src/server/launchpad/t_resources.js

This goes with #376, and deals with the corresponding tests.

Convert internal LP client tests to async/await

---

src/common/containers/with-repository.js
test/unit/src/common/containers/t_with-repository.js

Fixes #373
The issue was caused by `withRepository` container that was passing repository data from the store to build details page even if the repository in the store was different from the one in the URL.
With this PR we make sure to properly set repository in the store when it doesn't match the one in the URL. Also if these repos don't match child component is not rendered (until value in the store is properly propagated).

Fixes for passing repository to build details page

---

src/server/middleware/trusted-networks.js

`''.split(',')` returns `['']`, not `[]`, and `''` doesn't parse as an
IP address range.

Fix TRUSTED_NETWORKS parsing

---

.gitignore
Makefile
charm/charm-deps
charm/config.yaml
charm/dependencies-devel.txt
charm/layer.yaml
charm/metadata.yaml
charm/reactive/snap-build.py
charm/templates/knexfile.js.j2
charm/templates/snap-build_systemd.j2
knexfile.js
migrations/20170302155852_user.js
npm-shrinkwrap.json
package.json
src/config/defaults.js
src/server/db/index.js
src/server/db/models/github-user.js
src/server/handlers/github-auth.js
test/routes/src/server/routes/t_github-auth.js

We now use the Bookshelf ORM and the Knex query builder, which gives us
a promise-based interface to multiple databases with minimal
boilerplate.
In development, we use SQLite by default, since that involves minimal
setup.  In staging and production, we use PostgreSQL, so this comes with
charm changes to ensure that we have access to a suitable database.
At the moment, user information is saved to both the session and the
database.  This is obviously duplicative, and we should perhaps consider
having just an ID in the session and fetching the rest from the database
as needed.  Similarly, perhaps some of the things we use memcached for
would make more sense in a more persistent database instead.
Part of #360.

Store GitHub user information in a database

---

src/common/components/build-row/index.js
src/common/components/repository-row/index.js
test/unit/src/common/components/build-row/t_build-row.js
test/unit/src/common/components/repository-row/t_repository-row.js

Fixes #416 
Because we currently only show log of completed builds, we want to 'hide' build details pages until log is available.
This mean links from dashboard or repo details to build pages should only be rendered when build log is already available.

Link only to completed builds

---

charm/dependencies-devel.txt

Otherwise the sqlite3 module can't be built in JenkaaS, which can't
download precompiled binaries.

Add build-essential to dependencies-devel

---

charm/charm-deps

This adds the `trusted_networks` charm configuration option, which we
use.

Upgrade to layer-ols r17

---

Makefile

Our dependencies now include sqlite3, which needs to build a dependency
using node-gyp.  By default this will try to fetch a header bundle from
nodejs.org, which isn't permitted in JenkaaS.  Tell it that it can use
the perfectly good headers in /usr instead.

Use "npm install --nodedir=/usr" in charm build

---

charm/reactive/snap-build.py
charm/templates/knexfile.js.j2

Exports from `knexfile.js` are keyed by `NODE_ENV` rather than by the
environment name, which in the case of staging is "production".  Handle
this.
(Getting rid of {staging,production}.env entirely would avoid the
duplication here; that's #276.)

Fix generated knexfile on staging

---

charm/reactive/snap-build.py

More trouble from the disconnect between the environment name and
NODE_ENV on staging: migrate:latest needs to be passed NODE_ENV in its
--env option rather than the environment name.

Fix knex migration on staging

---

src/server/metrics/github-users.js
src/server/metrics/index.js
src/server/server.js
test/unit/src/server/metrics/t_github-users.js

This shows the number of GitHub users who have ever logged in (since the
creation of the database table, at least).
Part of #360.

Add a bsi_github_users_total metric

---

src/common/reducers/snaps.js

babel-polyfill in webpack config means js-core https://github.com/zloirock/core-js, which means we can find here rather than filter?

Array.prototype.find() anyone?

---

charm/reactive/snap-build.py

It can be None here when running from the `db-admin-relation-changed`
hook.

Sanity-check pgsql.master before using it

---

src/common/containers/landing.js

* updated images per design
1. go to the landing page
2. see the banner image is - https://assets.ubuntu.com/v1/4feda3a7-header_strokes-to-path.svg
3. see the workflow image is - https://assets.ubuntu.com/v1/9ec98fa2-workflow_text-to-path.svg
Fixes #362

update banner and workflow images on landing page

---

docs/memcached.md
src/server/handlers/github.js
src/server/handlers/launchpad.js
test/routes/src/server/routes/t_github.js
test/routes/src/server/routes/t_launchpad.js

Fixes #297
It's not a UI change, but something that is needed to allow us to provide a link to edit snapcraft.yaml file in repo.
Snapcraft.yaml can currently be in one of 3 possible locations, so we not only need to know that file exists, but also where it is in repository.
`snapcraft_data` that we pass together with snap (enabled repository) currently contains just a snap `name` from snapcraft.yaml. While it was meant to be a representation of contents of snapcraft.yaml it seems the only reasonable place to add the file path.

Added snapcraft.yaml path do snapcraft_data

---

src/server/middleware/trusted-networks.js
test/unit/src/server/middleware/t_trusted-networks.js

It turns out that `ipaddr.subnetMatch` can only be asked to match
against networks of the same address kind, so if both IPv4 and IPv6
ranges were present in `TRUSTED_NETWORKS` then we would crash as soon as
we reached that point in the matching process.  Fix this.

Fix crash when both IPv4/6 networks are trusted

---

charm/reactive/snap-build.py

`configure` should only run when the `ols.pg.configured` state is set;
otherwise it's possible for this function to run, set the unit's status
to "active", and then for `ols_pg_configured` to run immediately
afterwards and set the status back to "waiting".  This is usually
harmless since hook retries will cause things to settle down eventually,
but it can slow down deployments by several minutes.

Tighten up reactive state handling slightly

---

charm/charm-deps
charm/layer.yaml
charm/reactive/snap-build.py

This won't become active until we set `promreg_url` and
`promreg_authtoken` in the Mojo spec, and we need to get an
authentication token and get firewall changes landed before we can do
that, but we might as well prepare for it now.
Part of #360.

Register appservers for Prometheus monitoring

---

charm/config.yaml
charm/reactive/snap-build.py
charm/templates/snap-build_systemd.j2

Monitoring the individual appservers turns out to be awkward because
we'd have to expose the relevant port in security groups.  We don't
actually care about the per-unit monitoring anyway, only the
application-wide metrics that come from the database and can be
published by any appserver, so let's just point the monitoring server at
the frontend instead.
This requires the charm to know the application's base URL.  For this,
I've taken a dual approach: firstly, I've added a hack to fish it out of
the environment file for now, to minimise the number of steps needed to
get this deployed; and secondly, I've added a `base_url` charm
configuration option, which fits with the general goal of eventually
superseding the `.env` files.
Part of #360.

Point Prometheus at public frontends

---

charm/reactive/snap-build.py

Prometheus isn't going to work very well with the host set to
`build.staging.snapcraft.io%0A:80`.

Strip trailing newline from computed base_url

---

src/common/components/vanilla/breadcrumbs/breadcrumbs.css
src/common/components/vanilla/breadcrumbs/index.js
src/common/containers/build-details.js
src/common/containers/builds.js
src/common/containers/container.css

Fixes #310
Repo details page:
Build details page:

Added vanilla based breadcrumbs to build pages

---

src/server/metrics/github-users.js
test/unit/src/server/metrics/t_github-users.js

This is needed to make this metric selectable on
snappy.kpi.canonical.com.

Add metric_type="kpi" label to GitHub users metric

---

src/common/containers/build-details.js
src/common/containers/with-repository.js
src/common/containers/with-snap-builds.js
test/unit/src/common/containers/t_with-repository.js

Fix #395 
Empty build page seemed to be caused by BSI lowercasing repository name from URL, so instead of `MailHog` we were looking for snap for `mailhog` repo, which doesn't exist.
Therefore no snap was found and no builds shown.
Also, there was an issue that error was not passed to wrapped component, so whole page was rendered blank instead of properly showing error message (what snap cannot be found) - that would make it a lot easier to debug what is causing the problem.

Fix #395: Removed unnecessary lowercased URL params

---

src/common/components/help/install-snap/index.js
src/common/containers/build-details.js
test/unit/src/common/components/help/t_install_snap.js

Fixes #355 - reusing existing help box to show build debug instructions

---

src/server/db/index.js
src/server/db/models/github-user.js
src/server/db/models/index.js
src/server/handlers/github-auth.js
src/server/metrics/github-users.js
src/server/metrics/index.js
test/routes/src/server/routes/t_github-auth.js
test/unit/src/server/metrics/t_github-users.js

* Use the Bookshelf registry plugin
This will mean fewer problems with circular dependencies if the database
schema gets more complicated.
* Run database queries in transactions
At the moment we have no particular need for cleanly rolling back
transactions, but we will soon, and we might as well put good practice
in place now.
I considered using `bookshelf-transaction-manager` to avoid the
`{ transacting: trx }` boilerplate, but it ended up being much more
trouble than it was worth: it doesn't currently wrap all the Bookshelf
model/collection methods, which makes it very confusing and error-prone
to use.

Clean up database handling code

---

src/common/components/repository-row/index.js
test/unit/src/common/components/repository-row/t_repository-row.js

Links on build status in my repos list should link to repo details to show builds for all architectures, not just single build.

Fix #302 - build status should link to repos page

---

src/common/components/repository-row/dropdowns/register-name-dropdown.js

Some names may be reserved by Canonical.
We should show extended error message explaining how to claim the reserved name.
To test it try reserving name 'zeppelin'.

Fix #401 - show extended message for reserved names

---

src/common/components/repositories-home/index.js
test/unit/src/common/components/repositories-home/t_repositories-home.js

Fixes #507 
Showing spinner on 'My repos' until snaps data is properly fetched.
If user has no repos (because they never added one or removed all of them) they will be redirected to select repositories.
Current solution has one case when it works a bit weird (may be considered a bug):
When user has some repositories and adds new one, then they move back from 'select repositories' to 'my repositories' they will see their old list of repos (without the new one) until list gets refreshed.
There is also no spinner of any kind (because we don't want to show spinner during polling).
So there is a visual delay between adding a repo and it being rendered no the list.

Properly show spinner when user has no repositories

---

.eslintrc.js
src/common/components/help/install-snap/index.js
src/common/components/repository-row/dropdowns/register-name-dropdown.js
src/common/components/repository-row/dropdowns/unconfigured-dropdown.js

`<a target=_blank />` is considered a security risk, we don't really have user generated content but doesn't hurt to have the rule.
More about `rel=noopener` here: https://mathiasbynens.github.io/rel-noopener/
Lint rule is defined here: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md

add eslint rule for no-target-blank in jsx, fix occurrences

---

charm/templates/snap-build_systemd.j2
environments/test.env
src/config/defaults.js
src/server/metrics/github-users.js
src/server/metrics/labels.js
test/unit/src/server/metrics/t_github-users.js

This lets us select between staging and production in Grafana.
(Technically we can do this already due to automatically-applied labels,
but `instance="build.snapcraft.io:80"` is a terribly ugly way to go
about it; `environment="production"` is much nicer.)

Add the environment name as a metric label

---

charm/charm-deps

The only effective difference here is to remove invalid characters from
the Nagios service description.  For the full diff, see:
https://bazaar.launchpad.net/~ubuntuone-pqm-team/ols-charm-deps/layer-ols-http/revision/9?compare_revid=3
I'm avoiding newer revisions for the time being since those will require
either a code change (to implement `/_status/check`) or a Mojo spec
change (to suppress the `httpchk` option).

Bump layer-ols-http to r9

---

src/common/components/header/index.js
test/unit/src/common/components/header/t_header.js

A _partial_ fix for #318. The link in the header should no longer be necessary, because (thanks to #310) it is now present in the breadcrumbs on every other page.

Removes 'My repos' link from the header

---

src/common/components/select-repository-list/index.js
src/common/components/select-repository-row/index.js
src/common/components/select-repository-row/selectRepositoryRow.css
src/common/helpers/repositories.js
src/common/selectors/index.js
test/unit/src/common/components/select-repository-list/t_select-repository-list.js
test/unit/src/common/components/select-repository-row/t_select-repository-row.js
test/unit/src/common/selectors/t_selectors.js

Fixes #313 
Adding spinner to 'Add' repository button and disabling whole repositories form while waiting for response.
> https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.43owh6tjv12q: “When you choose ‘Add’, everything in the dialog should become disabled, and the text of the ‘Add’ button should change to a spinner.”

Added spinner on 'Add' repository button

---

migrations/20170314122717_user-metrics.js
src/common/actions/register-name.js
src/server/db/models/github-user.js
src/server/handlers/launchpad.js
src/server/handlers/store.js
src/server/handlers/webhook.js
src/server/metrics/developer-uptake.js
src/server/metrics/index.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/server/metrics/t_developer-uptake.js

We now track developers adding/removing snaps, registering snap names,
and requesting builds, and emit aggregate metrics indicating how many
developers have reached various stages in the process.
Fixes #446.

Add developer uptake metrics

---

charm/charm-deps
charm/layer.yaml
charm/reactive/snap-build.py

It turns out that auto-registering with IS Prometheus doesn't meet our
needs since it doesn't federate with snappy.kpi.canonical.com, and we
had to just have snappy.kpi.canonical.com manually configured to fetch
metrics from us instead.  As such, we no longer need the Prometheus
registration layer.

Remove Prometheus registration layer

---

scripts/create-launchpad-credentials

BSI can be usefully configured locally to point to Launchpad instances
other than production for the purpose of testing various things: staging
mostly works (modulo a snap-proxy problem that'll be fixed soon),
dogfood works, and it's even possible to use a local development
instance.  To make such things easier, add a `--launchpad` option to
`scripts/create-launchpad-credentials`.
Production is still the right choice for BSI staging for the moment,
since Launchpad staging is reset weekly and would require some
reconfiguration to preserve BSI credentials across the reset, but it may
be worth looking into that in future.

Add instance option for LP credentials

---

npm-shrinkwrap.json
package.json
src/common/actions/snaps.js
src/common/middleware/call-api.js
src/common/reducers/snaps.js
src/common/store/configureStore.js
src/common/store/index.js
src/server/handlers/universal.js
src/server/helpers/html.js
src/server/middleware/csrf-token.js
src/server/routes/launchpad.js
src/server/server.js
test/helpers.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/actions/t_snaps.js
test/unit/src/common/middleware/t_call-api.js
test/unit/src/common/reducers/t_snaps.js

- Added new Express middleware to generate and verify CSRF tokens
- Added global window.__CSRF_TOKEN__ variable for application to consume
token from server
- Added new API_CALL redux middleware to encapsulate API requests and pass tokens
- Migrated FETCH_SNAPS and REMOVE_SNAPS chain of events to API_CALL
- Fixed snaps reducer to work with API_CALL middleware
- Added unit tests

495: CSRF tokens

---

docs/memcached.md
environments/test.env
migrations/20170320131245_builds-released-metric.js
src/config/defaults.js
src/server/db/models/github-user.js
src/server/handlers/github.js
src/server/handlers/launchpad.js
src/server/handlers/webhook.js
test/routes/src/server/routes/t_launchpad.js
test/routes/src/server/routes/t_webhook.js

We do this by configuring a webhook on Launchpad snaps and counting
events where `store_upload_status` is "Uploaded".  (We could use the
information provided by this webhook for some more things in future to
reduce polling, although that would also require putting some more
thought into ordering guarantees; since "Uploaded" is a terminal status
we don't need to think about that too hard in this case.)
Of course there are lots of existing snaps that need to have the webhook
added, and it's also possible that we might create the snap and then
fail to create the webhook.  We don't currently have any infrastructure
for running scripts or periodic jobs, which would be a better way to
handle this; but as a reasonably lightweight workaround for these
problems, `/api/launchpad/snaps/list` also …

Add metric for builds released to edge

---

.vscode/settings.json
src/common/components/header/header.css

The beta flag needs to align with the baseline of the word mark and not
been in a superscript position as it is now.

Adjust the alignment of the beta flag

---

src/server/handlers/universal.js

This has recently started causing `HEAD /` requests to fail on staging.
I'm not clear on why this has only started happening recently, but I
think this code has been wrong for some time: `handleMatch` is always
called and emits a response in all cases, so there's no reason to fall
through to other routes here (except for error-handling middleware,
which will still be called on unhandled exceptions).
Fixes #583.

Drop next-route fallthrough from universal handler

---

test/unit/src/common/components/select-repository-row/t_select-repository-row.js

select-repository-row has the repository as a prop and can figure out if it should be selected or not from that, it can't know if it's enabled, so that has to be passed from the parent where the comparison of snap and repo list (selector) works that out.
Use simulate('change') to trigger the onChange handler.
FWIW I find the verbose naming of these tests a little hard to parse on a test by test basis.

fix select-repository-row tests

---

test/unit/src/common/reducers/t_snaps.js

I think I want a shared lib of responses and action payloads (or maybe we generate the payloads from action creators using the lib of responses?)

fix success response fixture

---

src/common/components/beta-notification/trigger.js

Fix #563
There is a potential issue of notification being in flow moving the users content reported in #558.
We can address it separately if needed.

30 seconds beta notification delay

---

src/common/reducers/snaps.js

We don't have explicit removal from the index right now, and we only use the snap index in one place (enabled repos selector), so dropping `union` means the ids list is in sync with and depends on the server response.

Snap delete bug

---

src/common/components/help/install-snap/index.js
src/common/containers/build-details.js
src/common/helpers/snap-builds.js
test/unit/src/common/components/help/t_install_snap.js
test/unit/src/common/helpers/t_snap-builds.js

Launchpad exports this information now, so we can restore the
`--revision=` part of `snap install` instructions.

Show store-assigned revisions of builds

---

package.json
src/common/actions/auth-store.js
src/common/components/build-status/index.js
test/unit/src/common/actions/t_auth-store.js

Without this, people in a timezone sufficiently far west of UTC will get
macaroons that expire before the start of their validity period.
I experimented with some timezone mocking libraries, but couldn't get
anything to work very well.  The easiest approach seems to be to just
run the whole test suite in `TZ=US/Pacific`, which should be enough to
shake out most timezone handling bugs.
Fixes #527.

Do all time manipulations in UTC

---

src/common/components/first-time-heading/index.js
src/common/components/repositories-home/index.js
src/common/components/repositories-list/index.js
src/common/components/select-repositories-page/index.js
src/common/components/select-repository-list/index.js
src/common/helpers/repositories.js
src/common/reducers/entities/index.js
src/common/reducers/entities/snap.js
src/common/reducers/snaps.js
src/common/selectors/index.js
test/unit/src/common/components/repositories-home/t_repositories-home.js
test/unit/src/common/components/repositories-list/t_repositories-list.js
test/unit/src/common/reducers/entities/t_entities.js
test/unit/src/common/reducers/entities/t_snap.js
test/unit/src/common/reducers/t_snaps.js
test/unit/src/common/selectors/t_selectors.js

First part of #465
- removes snaps objects from `snaps` reducer and only keeps list of `ids` there
- snaps data is now fully kept in `entities`
- updated relevant components, selectors, etc to accommodate the change
This should be a good first step refactoring, further work is needed around actions, API calls etc.
As described in TODO items in code and in description of #465

Refactor snaps redux store

---

src/server/handlers/subscribe.js

`fetch` doesn't support proxies, so is no good in staging/production
where we need a proxy to talk to MailChimp.
Fixes #617.

Rewrite subscribe handler using request

---

package.json
src/common/actions/repository.js
src/common/components/select-repository-list/index.js
src/common/middleware/call-api.js
src/common/reducers/entities/repository.js
src/server/handlers/github.js
src/server/routes/github.js
src/server/routes/launchpad.js
test/routes/src/server/routes/t_github.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/middleware/t_call-api.js
test/unit/src/common/reducers/entities/t_repository.js

- Refactored actions to use CALL_API middleware
- Rewrote CALL_API middleware to use promises instead of async / await
- Renamed single repo action type identifiers
- Changed webhook-already-created response to return 200
- Added verify token middleware to add repo endpoint
- Added verify token middleware to webhook endpoint

614: Add CSRF tokens to single repo API calls

---

src/common/components/repository-row/dropdowns/register-name-dropdown.js
src/common/components/repository-row/index.js
test/unit/src/common/components/repository-row/t_repository-row.js

Fixes #669 
If snapcraft.yaml is not available we are now suggesting snap name to register based on repo name.

Suggest snap name based on repo name

---

src/common/components/private-repos-info/index.js
src/common/components/repositories-list/index.js
src/server/handlers/github-auth.js
src/server/handlers/github.js
src/server/handlers/launchpad.js
test/routes/src/server/routes/t_github-auth.js
test/routes/src/server/routes/t_github.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/components/repositories-list/t_repositories-list.js

This shows organisation repositories for which the user has admin
permissions in the add-repositories dialog, and shows organisation
repositories that the user can write to on the my-repositories page.
Various aspects of the UI will need to be tidied up in future PRs, but
this at least gets us started.
We now request the `read:org` scope from GitHub, which allows us to tell
which organisations a user is in.
I also included a change to sort repository list rows alphabetically,
since given the rest of this change I was seeing odd results without
that.
Fixes #620; fixes #648.

Add baseline support for organisation repositories

---

src/server/routes/index.js
src/server/server.js

@katiefenn noticed that the app is broken because the routes removed in #272 were still being referenced :cry: 
This PR removes those references. Ideally we'd have test coverage of these - I think we should land this first, then look at increasing coverage as a tech debt item?

Don't try to use removed store routes

---

src/common/components/repositories-list/index.js
src/common/components/repository-row/dropdowns/register-name-dropdown.js
src/common/components/repository-row/index.js
src/common/helpers/snap-builds.js
test/unit/src/common/helpers/t_snap-builds.js

Fixes #670
Passes published status (based on build store upload status) to name register dropdown to warn when renaming already published snap.

Warning when renaming published snap

---

src/common/components/repositories-list/index.js
src/server/handlers/universal.js

Even though we store macaroons in browser storage app did not properly check if user is already signed in after full page reload.
It was caused by `authenticated` flag being undefined in initial state rather then being `null` (as app code expected).

Properly propagate store authenticated initial state

---

src/common/actions/organizations.js
src/common/components/select-repositories-page/index.js
src/common/reducers/user.js
src/server/handlers/github.js
src/server/routes/github.js
test/routes/src/server/routes/t_github.js
test/unit/src/common/actions/t_organizations.js
test/unit/src/common/reducers/t_user.js

Part of #680
API to refresh list of user orgs (in cache, session and redux store) in case access was changed on GitHub side.

API to refresh user orgs

---

package.json
src/common/actions/snap-builds.js
src/common/middleware/call-api.js
src/common/reducers/snap-builds.js
src/server/routes/launchpad.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/actions/t_register-name.js
test/unit/src/common/actions/t_snap-builds.js
test/unit/src/common/reducers/t_snap-builds.js

- Replaced calls to fetch in snap-builds actions with CALL_API
middleware
- Changed CALL_API to not require options anymore (they're options!)
- Added CSRF token checks to snap-builds endpoints
- Fixed tests to work with changes to API calls
- Added new task for watching unit tests

676: Added csrf tokens to remaining API calls

---

src/common/containers/builds.js
test/unit/src/common/containers/t_builds.js

If there are no published builds yet, don't show the "To test this snap"
instructions.  Fixes #528.

Remove confusing advice from repo page

---

src/common/components/help/help-install-snap.js

The spec has the copy linked and with no external link icon.

update "install snapd" link

---

src/common/actions/auth-store.js
test/unit/src/common/actions/t_auth-store.js

We switched to the forked store recently, which means that the host part
of STORE_API_URL is `dashboard.snapcraft.io`, but it turns out that the
forked store still issues macaroons whose location is
`myapps.developer.ubuntu.com`, presumably out of concerns for
compatibility.  When extracting the `expires` caveat, we therefore need
to extract one that matches the macaroon's location, rather than
assuming that the location is going to match the host that we thought we
were contacting.
Fixes #719.

Fix store expiry check

---

src/common/components/repositories-list/index.js
src/common/components/repository-row/dropdowns/name-mismatch-dropdown.js
src/common/components/repository-row/dropdowns/remove-repo-dropdown.js
src/common/components/repository-row/index.js
src/common/reducers/entities/snap.js
src/common/reducers/index.js
src/common/reducers/name-ownership.js
test/unit/src/common/components/repository-row/t_repository-row.js
test/unit/src/common/reducers/entities/t_snap.js
test/unit/src/common/reducers/t_name-ownership.js

Part of #646
Currently we only check name ownership for name in snapcraft.yaml - and we keep this status together with snapcraft.yaml data in redux store.
But for #646 we also need to check name ownership for registered names of snaps, so it would be better to have a separate store for keeping name ownership status per name.
This PR refactors current state of the app (name ownership of snapcraft.yaml name) into new name ownership reducer, where in future also register names ownership may be kept.

Name ownership reducer

---

mocks/service/github/index.js
mocks/service/github/responses.js

Update mock GitHub to actually match enough of the real GitHub to placate the app (enough to pick a repo)
How do we keep this from breaking going forward  :question: Do we even want to? :thinking:

Fix mock GitHub service to return data that is used by the app.

---

src/common/actions/auth-store.js
src/common/actions/register-name.js
src/common/components/repository-row/index.js
src/common/reducers/name-ownership.js
test/unit/src/common/actions/t_auth-store.js
test/unit/src/common/actions/t_register-name.js

As suggested by @cjwatson `/store/account` API response (that we already make after user signs in) already contains list of names registered by given user.
So we can pre-populate list of names owned by given user with this information before we attempt to verify ownership of any other name.

Get registered names from account info response

---

src/common/components/repository-row/index.js
src/common/reducers/name-ownership.js
test/unit/src/common/reducers/t_name-ownership.js

Found when debugging issues with #738.
If name ownership failed (returned an error) for any reason we were attempting to (immediately) fetch it again. This was resulting in loops of /register-name API calls failing in the same way.
We don't have any means to debounce such repeated calls or postpone reloading the data in case of error, so the best way to deal with that would be not to try again if error was returned.
Name ownership will be refreshed next time user reloads whole page or signs in again.

Don't attempt do reload name ownership if previous failed

---

mocks/service/github/index.js

The mock GitHub service fails to respond sensibly to a request for `snap/snapcraft.yaml` when it can just 404 instead. This makes the fake simulate a `snapcraft.yaml` but a missing `snap/snapcraft.yaml`.

Simulate a missing snap/snapcraft.yaml

---

migrations/20170503223139_repository.js
src/server/db/models/github-user.js
src/server/db/models/index.js
src/server/db/models/repository.js
src/server/handlers/launchpad.js
src/server/handlers/webhook.js
test/routes/src/server/routes/t_launchpad.js
test/routes/src/server/routes/t_webhook.js

Keep track of who registered each repository with build.snapcraft.io in
a new Repository table, and attribute `builds_requested` and
`builds_released` activity to that user.  Catch up with existing
repositories via the `/api/launchpad/snaps/list` handler.
This isn't necessarily perfect since the publisher can be reassigned in
the store without us noticing, but this is tolerable since it's only for
metrics.
The `Repository.snapcraft_name` and `Repository.store_name` columns
aren't immediately needed for this, but will be useful for future work
such as #706.
Fixes #621.

Attribute organization repo activity to registrant

---

src/common/components/repository-row/dropdowns/remove-repo-dropdown.js
src/common/components/repository-row/index.js
test/unit/src/common/components/repository-row/dropdowns/t_remove-repo-dropdown.js

Fixes #646
Final UI part of #646. If repo has registered name user needs to sign in before removing it.
Only user who registered the name is able to remove given repo.

Prevent other users from removing registered snap

---

Makefile

ols-jenkaas is set up such that code running in the containers doesn't
currently have a git identity configured, so the build-charm jobs
sometimes fail depending on whether git manages to auto-detect some
semblance of a reasonable identity.  Work around this by forcing the
correct identity, although this is hardcoding production configuration
that ought to live elsewhere.

Work around ols-jenkaas build-charm failures

---

src/server/handlers/launchpad.js

The manual Knex deletion code we were using previously apparently
compiles to something that isn't quite syntactically valid for
PostgreSQL, so fall back to a slower Bookshelf-based fetch/destroy pair
instead.

Fix Repository row deletion with PostgreSQL

---

README.md
package.json
src/config/defaults.js

- Removed references to the service mock
- Revised instructions for setting up test credentials for the GitHub
and Launchpad services

Readme Review

---

src/common/components/badge/badge.css
src/common/components/badge/index.js
src/common/components/share/index.js
src/common/containers/builds.js
src/common/containers/container.css
src/server/handlers/badge.js
src/server/routes/badge.js
test/routes/src/server/routes/t_badge.js

Fixes #675
Showing snap build badge on repo page with a copy Markdown button.

Showing badge on repo page. 

---

src/common/middleware/call-api.js
src/common/reducers/snap-builds.js
test/unit/src/common/middleware/t_call-api.js
test/unit/src/common/reducers/t_snap-builds.js

Fixes #774 
What seemed to be just a small issue with getting error in reducer turned out to be a bigger issue with our `callApi` middleware.
This middleware currently both dispatches an action of given type and returns a promise (resolved if fetch is successful or rejected in case of an error).
The problem was, that in most cases when we handle API responses and expect reducer to handle the error we didn't expect and catch the rejected promise. Which resulted in uncaught promise rejections almost every time API returned an error (even when we 'expected' it and passed to reducer).
So, as the main part of this PR the call API middleware needed to change a bit so it either dispatches an action (if given a type) or returns a resolved/rejected promise (if action type is not given as setup).

Fix error handling in callApi middleware

---

src/server/handlers/github-auth.js
test/routes/src/server/routes/t_github-auth.js

Fixes #780
Using metrics data (number of added snaps) to redirect users on sign in: to select-repositories if they never added any snap or to dashboard if they have (or did have) any snaps.
As discussed in #780 this will have a consequence that users will not be able to get to clean 'first time' state after they add any repo - unless we remove their data directly from the database.
This PR will allow to fix #675 without workarounds introduced in #782.

Redirect users on sign in based on if they ever added a snap

---

src/common/components/repository-row/index.js

This makes the message more specific without making it longer.

Fixes #703, changing 'Doesn't match' to 'Name mismatch'.

---

src/common/actions/snap-builds.js
src/common/containers/build-details.js
src/common/containers/builds.js
src/common/containers/with-snap-builds.js
src/common/reducers/snap-builds.js
src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/actions/t_snap-builds.js
test/unit/src/common/containers/t_builds.js
test/unit/src/common/reducers/t_snap-builds.js

Required to properly fix #655
Also part of postponed snap-builds refactoring #639 
Response from `findSnap` handler is now normalized.
Also builds list and build details components don't rely on duplicated nested `snap` object but properly get snap from existing `entities` store.
This is a refactoring task, so no new features added to test.
Unit tests should obviously pass.
Also builds listing (repo details) and build details pages should load without any errors both when navigating in the app and when fully reloaded (without pre-existing state).

Returning normalized snap response from findSnap handler

---

src/server/metrics/developer-uptake.js
test/unit/src/server/metrics/t_developer-uptake.js

Fixes #723
@cjwatson This seems to be adding `released_build` to `bsi_developer_update`, but it was all quite blindly based on existing code, so I'm not sure if anything else is needed for that.

Added builds_released to bsi_developer_uptake

---

src/common/components/select-repository-list/index.js
src/common/components/select-repository-list/styles.css

Fixes #755 
Even if there is no repos user should be able to cancel 'Add repos' and go back to 'My repos'.
1. Clean-up or remove app db (or make sure to sign in with fresh user).
2. Sign in and get redirected to 'Add repos' page
3. Cancel button should be visible, click it to get to empty 'My repos' page

Making sure Cancel button is always visible on Add repos page

---

src/common/actions/snaps.js
src/common/components/help/help-box.js
src/common/components/help/help-custom.js
src/common/components/help/help-install-snap.js
src/common/components/help/help.css
src/common/components/help/index.js
src/common/containers/builds.js
src/common/containers/container.css
src/common/reducers/entities/index.js
src/common/reducers/entities/snap.js
src/server/handlers/store.js
test/routes/src/server/routes/t_store.js
test/unit/src/common/actions/t_snaps.js
test/unit/src/common/containers/t_builds.js
test/unit/src/common/reducers/entities/t_entities.js
test/unit/src/common/reducers/entities/t_snap.js

Fixes #655
Currently only Twitter sharing is implemented. Others to be defined and implemented in #814.
1. Build a snap and wait for it to publish in the store
2. You should see 'No stable version yet' on 'My repos' page
3. Use the dashboard.snapcraft.io UI or snapcraft command line to release snap to stable channel
4. You should see 'To install the latest stable version' on 'My repos' page

Show install instructions for stable release of snap

---

src/common/helpers/github-url.js
test/unit/src/common/helpers/t_github-url.js

Entities reducer uses `getGitHubRepoUrl` to handle legacy actions, but if it's called with an action that doesn't have an `id` in payload it was causing `getGitHubRepoUrl` to throw an error.
This PR fixes the issue by returning early on empty input.

Fixed unhandled promise rejection when action had undefined repo url

---

src/common/components/private-repos-info/index.js
src/common/components/private-repos-info/private-repos-info.js
src/common/components/select-repositories-page/index.js

Part of preparations for #715 
This is a refactoring change that takes private repo info contents and moves it out of current popover to separate component, so it can be reused in different context (scrollable area of Add repos) in #715

Moved private repo info out of popover

---

src/common/components/private-repos-info/index.js
src/common/components/private-repos-info/private-repos-info.css
src/common/components/select-repositories-page/index.js
src/common/components/select-repositories-page/select-repositories-page.css
src/common/components/select-repository-list/index.js
src/common/components/select-repository-list/styles.css
src/common/components/select-repository-row/selectRepositoryRow.css

Part of #349
Updated styles of 'Add repos' box to make it scrollable. Leading us one step closer to desired design for this page.
Visual design it's based on:
https://github.com/canonical-websites/build.snapcraft.io/issues/715#issuecomment-302097730
Notes:
- currently not responsive (only desktop layout)
- 'Add repos' dialog height is static (not adapting to screen height as defined in spec) (#829)
Implemented:
1. run local server
2. sign in and go to 'Add repos'
3. wait for repos to load
4. list of repos should be scrollable and have styles as above

Making 'Add repos' list scrollable

---

src/common/containers/landing.css
src/common/containers/landing.js

- Resolved landing message text once logged in via GitHub. Text should now not conflict with Git terminologies
- Added more spacing between the text and other landing options, should improve readability and to find the content.
- Login via your GH account, then view the landing page. Next text and more spacing should be present. 
Fixes #733 #568

Resolved text issue and spacing issue with landing welcome message

---

npm-shrinkwrap.json
package.json

Updated version of `uuid` module to fix issues with enzyme@2.9.0 trying to import `uuid/v4` causing [failing travis build](https://travis-ci.org/canonical-websites/build.snapcraft.io/builds/245705391)
- Run `npm install`
- Run `npm test`
- Tests should pass.
Or just wait to see if travis build gets green ;)

Updated uuid version to fix issues with enzyme

---

src/common/components/header/header.css

- Amended the CSS to follow the same height styles from snapcraft.io to BSI.
- Open firefox and flick between the demo and snapcraft.io website, both headers should now match in height.
Fixes #800

Fixing height issues for the header, BSI should now match snapcraft

---

src/common/actions/repositories.js
src/common/components/select-repository-list/index.js
src/common/reducers/repositories.js
test/unit/src/common/actions/t_repositories.js
test/unit/src/common/components/select-repository-list/t_select-repository-list.js
test/unit/src/common/reducers/t_repositories.js

Updated "Add repos" to show spinner only if repos are not returned by API in 2 seconds.
Also 
- Set up a proxy or browser to fake a slow connection
- Go to "Add repos" page
- Should appear as empty list at first
- If repos are returned in less then 2 seconds they should appear (no spinner should be shown)
- If repos take more then 2 seconds spinner show show in the middle of Add repos dialog
Fixes #661
Fixes #855

Add repos spinner delayed by 2 seconds

---

src/common/components/select-repository-list/index.js
src/common/components/vanilla/button/button.css
src/common/components/vanilla/button/index.js
test/unit/src/common/components/select-repository-list/t_select-repository-list.js

Removed the onDocument click events for closing the missing / private repo dialog. Updated toggle link with aria details to help accessibility.
- Removed JS from ```select-repository-list/index.js``` file to stop clicking outside of dialog
- Updated markup on the renders on help link, including:
- - Aria labels to update what action is being taken on click
- - Removed anchor tags on the help link, this should be a button as anchor tags need to link to a new page or ID on the page and effect the URL.
- - Created link button style to look similar to an anchor link
- Go to the add repos …

Removed the onDocument click events for closing dialog

---

src/common/components/select-repository-list/index.js
src/common/components/select-repository-list/styles.css
test/unit/src/common/components/select-repository-list/t_select-repository-list.js

- Matches design and placement of the selected and total repos message on the add repos listing page
- Creates new function to pull in the amount of repos and what is selected with unit tests
- Go to the add repos page once logged in. When loading a message should show calculating your repos. Once complete the selected and total message should be present. 
Fixes #832

832 add repos amount number

---

package.json
src/common/style/vanilla/breadcrumbs.scss
src/common/style/vanilla/button.scss
src/common/style/vanilla/css/breadcrumbs.css
src/common/style/vanilla/css/button.css
src/common/style/vanilla/css/headings.css
src/common/style/vanilla/headings.scss

Added `vanilla-framework` and `node-sass` to dev dependencies to build patterns from vanilla as CSS modules.
Created a test pattern modules (buttons, headings, breadcrumbs) to build and added a npm script to run node-sass on them.
- Run `npm i` to install new dependencies
- Run `npm run build:vanilla-modules` to re-create files in `src/common/style/vanilla/css`
Fixes #863

Set up building Vanilla CSS modules

---

src/common/components/select-repository-list/index.js

[This text is intended](https://docs.google.com/document/d/1koTwI3cRr2S2vj5zHKKbR7aWxLRfShDVq2gHQ29cDyU/edit#heading=h.1uxwfvh1rvjz) to make sense in the context of, for example, “15 repos (Any missing?)” — the “any” means “any repos”.

Changes 'Anything missing?' to 'Any missing?' to match the spec

---

src/common/actions/repositories.js
src/common/components/select-repositories-page/index.js
src/common/components/select-repository-list/index.js
src/common/reducers/repositories.js
src/common/selectors/index.js
test/unit/src/common/actions/t_repositories.js
test/unit/src/common/components/select-repository-list/t_select-repository-list.js
test/unit/src/common/reducers/t_repositories.js
test/unit/src/common/selectors/t_selectors.js

Moving repos search functionality out of component to redux store.
- Go to add repos, you should (still) be able to search through repos
- Run `npm test`, all tests should pass
Fixes #330

Move repos search to redux

---

src/common/components/testimonial/index.js
src/common/containers/landing.js

- Removes non-sequitur alt text for citation logos (adjacent text already names organizations)
- Removes alt text for hero image (redundant with text immediately below)
- Adds alt text for target OS logos
- Adds alt text for workflow diagram (since text is embedded in the image)
- Adds empty alt attribute for quality illustration (to avoid noise when reading)
- Read the front page using a text browser or screenreader.
Fixes #874.

Fixes alt text for images on the front page (fixing #874)

---

src/common/components/repository-row/dropdowns/configuration-error-dropdown.js
src/common/components/repository-row/dropdowns/index.js
src/common/components/repository-row/index.js
src/server/handlers/github.js
src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js

* Returning details about error when snapcraft.yaml is invalid or not found in API response.
* Showing "Error" instead of "Not configured" when snapcraft.yaml is found but invalid.
- Sign in
- Add a repo with invalid snapcraft.yaml (try some indent error, duplicated keys, etc)
- Repo should show an "Error" in configured column
Fixes #548

Show error when snapcraft.yaml in invalid

---

src/common/components/repository-row/dropdowns/template-yaml.js
src/common/components/repository-row/dropdowns/unconfigured-dropdown.js
test/unit/src/common/components/repository-row/dropdowns/t_unconfigured-dropdown.js

- Amended the pre-populated YAML content when configuring a .yml file.
- Go to an unconfigured repo and click the dropdown and try to configure the YML. If the name isn't registered or is will give two outcomes as per issue #328  
Fixes #328

328 prepopulate yml with registed name

---

src/common/components/repository-row/index.js

Fixed a regression error that showed up when registering a name because of issue in checking errors in snapcraft data.
- Add a repo
- Try to register a name
No error should appear in user console, name should be properly registered.
Fixes #916

Properly checking snapcraft data existence when verifying name ownership

---

src/common/components/repository-row/dropdowns/template-yaml.js
src/common/components/repository-row/dropdowns/unconfigured-dropdown.js

- Replaced 'repo-name' out of the pre-populated yaml when a repo hasn't be registered at all
- Go to add repos and click and if a repo hasn't been configured click the get started template link for both a registered and un-registered repo
fixes #915

Removing the repo-name from the yaml output

---

src/server/scripts/poller.js
test/unit/src/server/scripts/t_poller.js

* Implemented LP snap build trigger
* Letting bookshelf/knex cast 'polled_at' according to the DB backend by passing a Date type (instead of a epoch).
```npm run build:scripts 2>&1 > /dev/null && npm run poll-repositories```

Triggering LP snap builds when repository or parts changes.

---

scripts/poller.js
src/server/scripts/poller.js
test/unit/src/server/scripts/t_poller.js

Workaround knex issue which hangs the poller script after the loop is complete.
See https://github.com/tgriesser/knex/issues/293
```npm run build:scripts 2>&1 > /dev/null && npm run poll-repositories -- --env=environments/dev.env```
It does not hang for few seconds (with sqlite) or forever (with pgsql) after completion.

Workaround for knex hanging after all repositories are polled.

---

src/server/handlers/github-auth.js
test/routes/src/server/routes/t_github-auth.js

Replaced `admin:repo_hook` with `write:repo_hook` OAuth permission scope.
- Revoke your dev application access on GH
- Sign in to the app, GH permissions screen should appear
- GH should ask for 'Read & write' instead of 'Admin' access to repo webhooks.
Based on research in #904

Replaced admin:repo_hook with write:repo_hook OAuth permission scope

---

src/common/components/build-history/buildHistory.css
src/common/components/build-history/index.js
src/common/containers/build-details.js
src/common/containers/builds.js
src/common/helpers/snap-builds.js
test/unit/src/common/components/build-history/t_build-history.js

Simple showing of build upload error message (as returned by API).
- Add a snap that builds but fails to publish
- Go the the build page
Fixes #714

Showing build upload error message on build details

---

src/server/handlers/launchpad.js

Making sure any error is properly propagated to response, so it's easier to debug issues.
Related to #936

Making sure all errors are properly sent in API responses

---

npm-shrinkwrap.json
package.json
src/common/style/vanilla/breadcrumbs.scss
src/common/style/vanilla/css/breadcrumbs.css
src/common/style/vanilla/css/button.css
src/common/style/vanilla/css/lists.css
src/common/style/vanilla/css/notifications.css

Updates Vanilla to 1.5.0 from NPM.
Also updated CSS built from vanilla.
- Run `npm i` (to update local npm modules)
- vanilla-framework 1.5.0 should be installed
- Go to a page with breadcrumb (for example build details page)
- Breadcrumb should have new vanilla styles (with blue links)
Fixes #940

Updated vanilla to 1.5.0 from npm and rebuilt vanilla css files

---

charm/reactive/snap-build.py
charm/templates/snap-build-poller_cron.j2
charm/templates/snap-build-poller_logrotate.j2

Deploying the poller (`npm run poll-repositories`) running hourly using the default configuration (dry-run, shared GH creds)

Deploying poller as a cronscript running hourly, default config.

---

test/routes/src/server/routes/t_launchpad.js

nock 9.0.19 started enforcing the specified request body
(https://github.com/node-nock/nock/pull/921), so tighten up our tests to
cope with that.

Fix nock request body matching

---

charm/templates/snap-build-poller_cron.j2
charm/templates/snap-build-poller_secrets.j2

Specifying secrets.env path in a way dash likes it (`. ./secrets.env`) so the cronjob for poll-repositories can finally runs.

Cope with dash specialties to source secrets.

---

src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js

Add automatic i386 builds. Giving developers control over which architectures they care to build for will come with the "build on" advanced grammar in snapcraft.yaml, hopefully before the end of the month. By extension this controls what architectures developers are happy to receive failed to publish emails for, they want the build badge to turn red for, etc.
See also https://github.com/canonical-websites/build.snapcraft.io/issues/902.

Add i386 builds by default

---

scripts/poller.js
src/server/scripts/poller.js

Also extending async-lock limit to 10k repositories for now, until we can think of a better solution.

Coping with async-lock limit errors.

---

src/common/components/repository-row/dropdowns/configuration-error-dropdown.js
src/common/components/repository-row/index.js
src/common/middleware/call-api.js
src/server/handlers/github.js
src/server/handlers/launchpad.js
src/server/helpers/prepared-error.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/components/repository-row/t_repository-row.js

Updated getting repo data (branch and snapcraft.yaml) not to fail when repo doesn't exist.
Marking repo with "Error" instead of "Not configured" when it doesn't exist (or is not accessible) on GitHub.
- Sign in
- Add repository to BSI
- Remove this repo from GH (or make it private)
- Go back to "My repos" page
Fixes #968

Fix showing repositories not available on GH

---

src/common/actions/auth-store.js
test/unit/src/common/actions/t_auth-store.js
test/unit/src/common/actions/t_register-name.js

In software-center-agent r4326, the store started responding with
"Developer profile is missing namespace." rather than "Developer profile
is missing short namespace."  It remains unfortunate that we don't have
a proper error code for this, but for the meantime let's at least adjust
to the current response.
Fixes #792; fixes #945.
QAing this will require creating a new account, so it's probably best to do this with a local build configured to point to staging.

Adjust for current "missing namespace" response

---

migrations/20171023112606_build_annotations.js
src/common/helpers/build_annotation.js
src/server/db/models/build_annotation.js
src/server/db/models/index.js
src/server/db/models/repository.js
src/server/handlers/launchpad.js
src/server/handlers/webhook.js
src/server/scripts/poller.js
test/routes/src/server/routes/t_launchpad.js
test/routes/src/server/routes/t_webhook.js
test/unit/src/server/scripts/t_poller.js

Recording `reason` (text) why builds are triggered (`/launchpad/snaps/request-builds`) and returning corresponding 'build_annotations' map when builds are retrieved (`/launchpad/builds`)

Implementing build annotations.

---

src/server/db/models/build_annotation.js
src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js

Working around knex/bookshelf being dumb (https://github.com/bookshelf/bookshelf/issues/853):
```
2017-10-27 19:00:55.094Z ERROR express "Error saving build annotations for 98768,98769,98770: error: insert into "build_annotation" ("build_id", "created_at", "reason", "updated_at") values ($1, $2, $3, $4) returning "id" - column "id" does not exist"
```

Fixing build_annotation PK ('build_id' instead of 'id')

---

src/common/components/build-row/buildRow.css
src/common/components/build-row/index.js
src/common/components/builds-list/index.js
src/common/helpers/build_annotation.js
src/common/helpers/snap-builds.js
src/common/reducers/index.js
src/common/reducers/snap-builds.js
test/unit/src/common/components/build-row/t_build-row.js
test/unit/src/common/helpers/t_snap-builds.js
test/unit/src/common/reducers/t_snap-builds.js

Added a build trigger column to builds table.
Design: https://github.com/CanonicalLtd/snappy-design-squad/issues/107#issuecomment-339019031
- Go to a repo page, builds trigger column should be visible
- Trigger new builds manually or via webhook - they should have proper build trigger shown
Fixes #990

Build trigger ui

---

src/common/components/help/help-install-snap.js
src/common/components/help/help-promote-snap.js
src/common/components/repository-row/dropdowns/unconfigured-dropdown.js

Now that docs for snapcraft have moved to new domain links to docs can be updated to avoid unnecessary redirects.
- Go to repo or build page with help boxes, docs links should link to docs.snapcraft.io
Fixes #969

Update snapcraft docs links

---

src/common/containers/app.js

As a follow up to #946 - dropping beta survey notification as well.
- Sign in
- Wait for 2 minutes - beta survey notification should not appear
Follow up on #946

Removing beta survey notification.

---

src/common/components/build-row/index.js
test/unit/src/common/components/build-row/t_build-row.js

Show build triggered by webhook as 'Commit' even if commit id is not known yet (from LP API).
Is hard to QA locally as it requires webhook to work.
- Commit to a repo added to BSI
- Open repo page, new builds show have 'Commit' as build trigger
- Once the build proceeds commit id should be shown as well
Fixes #999

Show 'Commit' as build trigger even if commit id is unknown.

---

src/common/components/header/index.js

Added href to sign out link in header to give it proper styling on hover (and to make it work without JS as well).
- Sign in
- Hover over Sign out link in header - it should have proper styles and hand cursor
Fixes #975

Added href to logout link to make it style properly on hover

---

README.md

As npm@5 introduces changes that don't seem to work with our outdated dependencies we need to make sure we run older version of npm (like npm@4).

Add npm version requirement to README

---

src/server/metrics/build-annotation.js
src/server/metrics/index.js
test/unit/src/server/metrics/t_build-annotation.js

E.g.`bsi_build{metric_type="kpi", reason="triggered-by-poller"}: <total>`.

Pushing metrics for build_annotations.

---

src/server/scripts/poller.js
test/unit/src/server/scripts/t_poller.js

Skip polling of parts specifying non top-level GH repositories as `source`, the API doesn't allow us to correctly verify changes and the vast majority of the case it's a static resource (release downloads or in-tree assets)
Fixes #1014

Only poll parts pointing to top-level repos.

---

npm-shrinkwrap.json
package.json
src/server/server.js

This is just enough to keep the ols-http charm layer happy.  I'm not
quite sure why this suddenly started to be a problem, but it's currently
causing deployments to fail to complete.
We don't have a good way to unit-test the full server app assembly, but
I've tested this manually by pointing curl at `/_status/check`, either
from localhost or from an IP address in `TRUSTED_NETWORKS`.

Add a trivial /_status/check endpoint

---

README.md

Require npm@3 because of issues with npm shrinkwrap (as in #1025)

Require npm@3 because of issues with npm shrinkwrap

---

npm-shrinkwrap.json
package.json
src/common/components/cookie-notification/index.js
src/common/containers/app.js

Adds a cookie policy notification to the page.
Based on `cookie-policy` (https://github.com/canonical-webteam/cookie-policy) module, but reimplemented to fit React and CSS Modules ecosystem.
- Cookie policy notification should show up on the bottom of the screen.
- Close it by clicking on X
- Check dev tools to see if cookie `_cookies_accepted` was added.
- Reload the page (notification should not appear if you still have the cookie)
- Delete `_cookies_accepted` cookie
- Reload the page (notification should appear again)
Fixes #786

Adds cookie notification based on Canonical cookie-policy module

---

src/common/components/build-row/index.js
src/common/containers/build-details.js
test/unit/src/common/components/build-row/t_build-row.js

Added a property to allow disabling link in BuildRow component.
So now, build id number doesn't unnecessary link to itself on build details page.
- Go to any build details page
- Build id should not be linked
Fixes #350

Disables self-link on build details page.

---

src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js

Properly initializes `builds_released` metric in db.
- Sign in and wait for you repos to load.
- If you have any already released builds they should be counted in `builds_released` metric in db.
Fixes #851

Properly initializes `builds_released` metric in db.

---

src/common/selectors/index.js
test/unit/src/common/selectors/t_selectors.js

Fixes checking for snapcraft.yaml data errors to properly detect not configured repos.
- Remove all the repositories
- Add one repository without snapcraft.yaml.
- Register a name for this repo.
- First steps heading on the top should ask for creating snapcraft.yaml and "Not configured" dropdown should be open for this repo (see screenshot below)
Fixes #1010

Fixes checking snapcraft data errors for first time flow.

---

src/common/containers/build-details.js

Removed `--edge` from snapcraft install instruction when build fails, as snapcraft is now available in stable channel.
- Go to a build details page of failed build
- See install instructions
Fixes #1028

Updates install instructions for snapcraft

---

migrations/20171219153812_user-email.js
src/server/db/models/github-user.js
src/server/handlers/github-auth.js
test/routes/src/server/routes/t_github-auth.js

Added email column to github_user database table.
Saving public user email from GitHub when user signs in.
- Make sure you have public email in your GH profile
- Sign in to BSI
- Your public email should be stored in db
Fixes #731

Adds a column to db to store public user email.

---

src/common/components/footer/index.js

I updated the copyright year of the footer.
- [List additional steps to QA the new features or prove the bug has been resolved]

Update the copyright year

---

src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/server/scripts/t_poller.js

To show builds in correct order we are fetching pending builds first and then append the list of completed builds.
- Go to repository page of come of your snaps
- Hit 'Build manually' - new pending builds should appear at the top of the page as latest
Fixes #1041

Fetches pending builds first before completed builds.

---

src/common/containers/app.js

The Launchpad build farm is mostly back to normal now.

Remove maintenance notification

---

src/common/components/first-time-heading/firstTimeHeading.css
src/common/components/traffic-lights/traffic-light.css

Fixes some small regression text positioning bug (after implementing max-width for headings and paragraphs).
- Have only one repo that is not configured yet (to see first time heading)
- Text in first time heading should be centered
Current (this text should be centered):
Fixed (properly centered):

Fixes centering of first time heading

---

src/common/components/header/index.js
src/common/style/vanilla/css/navigation.css
src/common/style/vanilla/navigation.scss

- updated header to new dark design, removes Tutorials link, updates sign in to 'Sign in with GitHub'
- Make sure header is dark
- Sign in
- Make sure user info in header is displayed correctly
Fixes https://github.com/CanonicalLtd/snapcraft-design/issues/274
Related to similar update on snapcraft.io: https://github.com/canonical-websites/snapcraft.io/pull/345
Header:
Signed in header:

New consistent header

---

src/common/style/vanilla/css/navigation.css
src/common/style/vanilla/navigation.scss

Fixes https://github.com/canonical-websites/snapcraft.io/issues/406
- Make window small (for mobile navigation)
- Open menu
- Hover on any item, there there should be no black hover on navigation

Fixes dark hover on mobile navigation

---

src/common/components/header/index.js

Properly highlight 'Build' link in navigation as selected
- Make sure 'Build' is selected in navigation (wherever you are in BSI)
Fixes #1075

Highlights 'Build' link in the navigation

---

src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js

The team providing a CLI for a popular public cloud is producing a snap and needs to build on arm64. They would like to use build.snapcraft.io for this.
This branch adds arm64 to the default set but does not back-populate configured repos to build for arm64.

Add arm64 builds

---

src/common/components/footer/index.js

Update snapd and snapcraft bugtracking links in footer to correctly point to launchpad
- Check if footer links to snapd and snapcraft correctly link to launchpad bugs
Fixes #1078

Update bugtracking links in footer

---

src/common/components/header/index.js

Styles the “Forum” link in the header as external, since the Forum is presented as a separate site (different header navigation, different colour scheme, different sign-in sessions, etc).
The build.snapcraft.io aspect of [snapcraft.io#522](https://github.com/canonical-websites/snapcraft.io/issues/522).

Styles header “Forum” link as external

---

src/common/components/repositories-home/index.js
test/unit/src/common/components/repositories-home/t_repositories-home.js

Polling repo's happens every 15 seconds, this reduces that frequency in an attempt to alleviate some issues caused by long repo lists.
- Make sure the app doesn't blow up after an hour or so.

Reduce polling frequency for repos

---

src/common/components/repositories-home/index.js
src/common/containers/builds.js
src/common/containers/with-snap-builds.js
test/unit/src/common/components/repositories-home/t_repositories-home.js

Disables polling for snaps and builds when page is inactive (tab is invisible).
- Go to My repos page
- Open "Network" panel of developer tools
- when page is visible every 30 seconds there should be requests for snaps and builds
- Switch to another tab, wait for more then 30 seconds (more then minute ideally)
- Switch back to 'My repos'
- Immediately when page is made visible snaps and builds should be fetched
- If you wait with page visible every 30 seconds there should be requests
- Switch to another tab and go back to 'My repos' quickly (in less then 30 seconds)
- There should be no …

Don't poll when page is inactive

---

src/server/middleware/csrf-token.js
src/server/routes/github.js
src/server/routes/launchpad.js

- removed verification of CSRF tokens from public `GET` API requests
- increased number of tokens stored in the session to allow multiple tabs opened at once
- Go to 'My repos'
- Open more then 10 tabs with BSI (My repos and different repos pages)
- All open tabs should work as expected, there should be no 'Unauthorized' errors when navigating around these tabs or when builds statuses are polled
Part of #1003

Better handling of CSRF tokens in session

---

src/common/actions/auth-error.js
src/common/actions/register-name.js
src/common/components/header/index.js
src/common/components/session-overlay/index.js
src/common/components/session-overlay/sessionOverlay.css
src/common/containers/app.js
src/common/middleware/call-api.js
src/common/reducers/auth-error.js
test/unit/src/common/middleware/t_call-api.js

- added detecting `401 Unauthorized` to API request handlers
- when expired session is detected (API returns 401) overlay is shown asking to reload and sign in again
- fixed unhandled sign out link in header (to properly clear session on sign out)
Not to wait 2h for session to expire `src/server/helpers/session.js:11` can be edited to change session cookie maxAge from 2h to something shorter like a minute or 10 seconds.
- Sign in with Github
- Possibly sign in into the Store on one of repos
- As long as session is not expired everything should work as expected, no overlay should be shown …

Detect expired session

---

src/server/handlers/github.js

Catch 404 error when snapcraft.yaml is not found in any of 3 possible locations and memcache this result (so we don't call GH API each time we poll for snaps).
It's a tricky one to QA without messing a bit with code and dev environment.
First of all, dev environment doesn't have memory cache (just nothing is cached), so either memcached needs to be run and configured or in memory cache (which can be enabled by changing `getMemcachedStub` into `getInMemoryMemcachedStub` in `helpers/memcached.js:82`).
To verify if memcached is used or GH API is called it's useful to add some logging into `helpers/github.js` `requestGithub` (which is called whenever any GH API is called) and/or inside `getSnapcraftData` in `handlers/github.js` which actually gets snapcraft.yaml data from memcached (line 181) …

Catch missing snapcraft.yaml error and memcache it

---

src/common/components/repository-row/dropdowns/dropdowns.css
src/common/components/repository-row/dropdowns/remove-repo-dropdown.js
src/common/middleware/call-api.js
test/unit/src/common/components/repository-row/dropdowns/t_remove-repo-dropdown.js

Allows removing repo even if registered name is owned by someone else, but warn user about doing it.
- Sign in
- Have a repo with a registered name owned by someone else (for example added by other org member)
- Try to remove it (Sign in to the store)
- You should see a warning explaining that you don't own the name and bug red button
- You should be able to remove the repo
Fixes #998

Allow removing repo with name owned by other user

---

src/server/handlers/launchpad.js

Part of #1006 
When debugging the timing of `findSnaps` response it turned out that (when nothing is memcached) one of the biggest bottlenecks is checking with LP that every repo/snap has a webhook.
When there is over 70 repos the whole response takes ~30 seconds, ~25 of which is spent asking LP to for webhooks for every snap one after another.
This PR changes for loop into `Promise.all` to check webhooks for all snaps concurrently.
- Sign in, wait for repos to load
- Everything should work as expected, if you have many repos they should probably load quicker then before
Part of fixes …

Batch "ensure webhook" calls to LP (for better performance)

---

src/common/components/first-time-heading/index.js
src/common/components/repositories-home/index.js
test/unit/src/common/components/repositories-home/t_repositories-home.js

Adds error notification to 'My repos' page when there is any error fetching list of snaps.
Currently if snaps listing request ends up with an error we show 'No repos' without any error message.
This at least gives user an idea that something is wrong.
To mock some server side error you can throw error inside `findSnaps` in `handlers/launchpad.js:556`. 
- Sign in
- Wait for snaps listing to return an error
- Error should show up above snaps list
- Error message will depend on whatever error was returned (and if API failing gave any error message)
Helps with #1006

Add error notification to My repos page

---

src/server/helpers/html.js

Use newly introduced SENTRY_DSN_PUBLIC for front-end reporting to sentry
- Add SENTRY_DSN_PUBLIC to you .env file
- Trigger some JS error (or `Raven.captureException(new Error("IGNORE: just testing sentry API"))` from console)
- Error should be sent to sentry project set up in SENTRY_PUBLIC_DSN

Use public sentry DSN for front-end error reporting

---

src/server/openid/relyingparty.js

Add some additional logging around association handle saving in session to possibly better understand reasons behind issues like #623
- Sign in with GH
- Sign in to store on one of the repos (to register name or delete it)
- Look into server logs/console - association handle saving/loading should be logged

Add some logging around association handle storing in session

---

charm/config.yaml

Set default sentry_dsn and sentry_dsn_public values to empty string (to avoid sentry_dsn_public being "None" when not set).

Set default sentry_dsn values to empty string

---

src/server/handlers/universal.js
src/server/middleware/csrf-token.js
test/routes/src/server/routes/t_github.js
test/routes/src/server/routes/t_launchpad.js

Attempting generate and store CSRF tokens was causing some race conditions when multiple tabs were opened at once and multiple tokens were stored into the session overriding each other.
It seems that generating token per request is not necessary. Single token per user session is secure enough (as per [synchronizer tokens](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_%28CSRF%29_Prevention_Cheat_Sheet#Synchronizer_.28CSRF.29_Tokens)). So this PR simplifies token generation to just use one token per authenticated user and fixes the issue with concurrent requests overriding each other tokens.
- View the site locally in your web browser at: …

Only store one token per session

---

src/server/handlers/github.js
src/server/helpers/github.js
src/server/helpers/prepared-error.js

We started noticing strange errors in logs that requests to GH to list user orgs fail:
`2018-06-06 11:21:30.534Z ERROR express "Error getting list of organizations from GitHub: Error"`
But because these issues cannot be reproduced outside of prod environment and current logging is not enough to find the cause this PR adds mode logging around getting organisations and makes sure our errors have better message then just 'Error'.
- Sign in, load your repos
- Here should be some additional logging about getting list or user orgs

Improve logging GH auth errors

---

src/common/components/repositories-home/index.js
src/server/handlers/launchpad.js

Making sure `findSnaps` and `findSnap` handlers fail early when session is expired not to call APIs unnecessarily with nonexistent auth token.
- Sign in to go to my repos page.
- Expire the session (for example by removing session cookie)
- Next time repos list is polled you should recieve 401 error, expired session should be detected
- When session is expired polling should be stopped (no further requests should be sent every 30 seconds)
Fixes #1117

Fail early on expired session

---

src/server/handlers/badge.js

Adds `no-cache` header to badge
- Go to a page of any repo
- Look at network panel for request for badge image
- Response should have `no-cache` value in `Cache-Control` header
Fixes #1101

Update badge cache headers as per GH expects it

---

src/common/actions/snap-builds.js

Seems that recently merged PR #1118 introduced a bug (Marking as critical as it's already on production).
Opening builds page in another tab was always ending with 'session expired' error, because session cookie was not sent with first API request.
This fixes that.
- Sign in
- On 'My repos' page open couple of repos in separate tabs
- They should open without showing that session is expired

Fix snaps API request credentials to make sure session cookie is sent

---

package.json
test/unit/src/server/handlers/t_github-auth.js

sinon added deep comparison of errors way back in 2.0.0 or so, which
needed a small test adjustment.

Upgrade to sinon 6.1.4

---

.github/PULL_REQUEST_TEMPLATE.md
mocks/service/github/responses.js
setup.sh
src/common/components/traffic-lights/index.js
src/server/handlers/github.js

The service is called GitHub, not Github.  Spell it consistently.

Fix spelling of GitHub

---

.env
.gitignore
environments/production.env
environments/staging.env
environments/test.env
src/common/components/header/index.js
src/common/components/vanilla-modules/icons/index.js
src/common/style/vanilla/css/navigation.css
src/common/style/vanilla/navigation.scss
src/config/defaults.js
src/server/handlers/github-auth.js
src/server/helpers/config.js
test/unit/src/common/components/header/t_header.js
test/unit/src/server/handlers/t_github-auth.js

This PR is one of the pieces required to make build.snapcraft.io and snapcraft.io seamless.
The idea is that `https://build.snapcraft.io` will redirect to `https://snapcraft.io/build`, however, after logging in to `https://snapcraft.io` you'll be able to click the 'Build with GitHub' link in the user menu which will redirect to `https://build.snapcraft.io/auth/authenticate`. Either starting the authentication dance, or redirecting to `https://build.snapcraft.io/user/{github_user}` where the navigation will be the same as on `https://snapcraft.io` (see the note below).
When a user logs out of either site they will be redirected to the log out of both, ending up back on the `https://snapcraft.io` homepage.
Fixes https://github.com/canonical-websites/snapcraft.io/issues/921
- Made the header …

Update navigation and redirect to snapcraft.io on login and logout

---

src/server/handlers/universal.js
src/server/routes/universal.js

- Redirect homepage to snapcraft.io/build
- Add to `environments/dev.env` the line: `SNAPCRAFT_URL=http://localhost:8004`
- Run snapcraft.io
- It should redirect you to: http://localhost:8004/build
- Try to login and set up your account
- Should work as usual
Fixes https://github.com/CanonicalLtd/snap-squad/issues/674

Redirect homepage to snapcraft.io/build

---

src/common/components/header/index.js

Added IoT to the navigation in preparation for https://github.com/canonical-websites/snapcraft.io/pull/994
- Pull the branch
- `npm start -- --environments/dev.env`
- Visit http://0.0.0.0:8083/auth/authenticate
- See the IoT link in the header

Add IoT link to navigation

---

src/common/components/header/index.js
src/common/containers/container.css

Fixes https://github.com/canonical-websites/build.snapcraft.io/issues/1133
Also made the site have the same 'max-width' as snapcraft.io with the same padding for 'container' items, to help align the sites.
- View the site locally in your web browser at: [http://0.0.0.0:8000/auth/authenticate](http://0.0.0.0:8000/auth/authenticate)
- Click around and make sure no page width is broken.
- Resize the browser to make sure everything fits as expected

Make site width the same as snapcraft.io

---

src/common/components/build-row/index.js
src/common/components/builds-list/index.js
test/unit/src/common/components/build-row/t_build-row.js

The "Build trigger" column is currently missing from the design
specification.  Design work for #556 calls for failed build requests to
have their request ID and error message rendered spanning the
"Architecture", "Duration", and "Result" columns; since failed build
requests still have a meaningful build trigger, having "Build trigger"
in the middle of this group of columns makes it hard to comply with that
otherwise-reasonable suggestion.
Moving "Build trigger" two columns to the left resolves this difficulty,
and seems to make just as much sense.  In fact, once we start using
build requests, it arguably makes more sense (because the build trigger
is known before the set of built-on architectures is known).

Move "Build trigger" column before "Architecture"

---

src/server/handlers/badge.js
src/server/handlers/launchpad.js
src/server/scripts/poller.js
test/routes/src/server/routes/t_badge.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/server/scripts/t_poller.js

`internalGetSnapBuilds` previously returned a somewhat mangled
`Collection` (a type used by the Launchpad web service client that
automatically handles batching and iteration of large collections).
However, this didn't make much sense here because the mangling meant
that the automatic batching wouldn't work quite right, and the callers
all just picked out the `entries` array anyway; it will make even less
sense as a `Collection` after upcoming work for #556.
We now just return an array instead.

Simplify internalGetSnapBuilds return value

---

src/common/components/build-request-row/index.js
src/common/components/build-row/index.js
src/common/components/builds-list/index.js
src/common/helpers/snap-builds.js
src/common/reducers/snap-builds.js
test/unit/src/common/components/build-request-row/t_build-request-row.js
test/unit/src/common/components/build-row/t_build-row.js
test/unit/src/common/helpers/t_snap-builds.js
test/unit/src/common/reducers/t_snap-builds.js

We will shortly need to change new snap build requests to be dispatched
more asynchronously, in order that Launchpad can fetch `snapcraft.yaml`
from the repository and decide which architectures the snap should be
built for.  This means that a snap can be in a state where it has
pending build requests (different from pending builds: for instance,
they don't have an architecture), and also where it has failed build
requests in its history (for example, because `snapcraft.yaml` is
malformed in such a way that Launchpad can't determine which
architectures it should be built for).
This prepares the UI layer for that work by ensuring that it can
understand the modified server responses and render build requests in
the builds list.  The server side hasn't been changed yet (that will be
a …

Prepare UI for upcoming build request changes

---

src/server/handlers/webhook.js
test/routes/src/server/routes/t_webhook.js

Launchpad sends a webhook when each build is created, and we now respond
to that by recording the link between the build and its parent build
request.
As is generally appropriate for webhooks, this is non-essential: if the
webhook delivery goes missing, we'll miss out on some metrics and won't
be able to present the correct build reason, but everything else will
still work.
Part of #556.

Extend webhook handler to support build requests

---

src/server/scripts/poller.js
test/unit/src/server/scripts/t_poller.js

If a build request is pending for a snap, we skip triggering new builds
just as we do if there have been recent builds.
Part of #556.

Extend poller to check pending build requests

---

src/server/handlers/webhook.js
test/routes/src/server/routes/t_webhook.js

Unlike the webservice API, keys in the webhook payload that contain URL
paths don't have "_link" appended to their names.  (I managed to get
this wrong despite having written both ends of the protocol.)
Unfortunately this is very hard to QA locally, since the webhook endpoint generally isn't accessible from LP instances, but you can compare against the [documentation](https://help.launchpad.net/API/Webhooks#Snap_build).

Fix LP webhook handling of build creation

---

docs/routes.md
src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js
test/routes/src/server/routes/t_webhook.js
test/unit/src/server/scripts/t_poller.js

This makes Launchpad responsible for asynchronously figuring out which
architectures the snap should be built for, thereby allowing us to
support Snapcraft's `architectures` keyword in `snapcraft.yaml`.
Fixes #556.
We'll need to walk through the whole workflow of requesting new builds to make sure that everything still works.

Request new builds using build requests

---

src/common/containers/build-details.js

This now uses the BuildsList component, so it shouldn't get out of sync
again.
Fixes #1066.
Look at a build details page; the table headings should match, and the cell under "Number" should remain as plain text rather than being a self-link.

Sync up table headings on build details page

---

src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js

I made a mistake while adding support for build requests: iterating over
a builds collection response from Launchpad iterates over the whole
collection, not just the current batch, so we ended up trying to return
all builds that had ever been created for a given snap and thus often
timing out.  We now take care to stop iterating once we've accumulated
enough builds.

Fix iteration of builds collections

---

npm-shrinkwrap.json
package.json
src/common/index.js
src/common/root.js

Among other things, this is needed in order to support a later upgrade
to babel 7; and the new API is rather more compact.

Upgrade to react-hot-loader 4

---

src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js

I did this a while back for everything on production, but forgot that
we'd also need to do this for newly-registered snaps.

Add ppc64el and s390x builds

---

.gitignore

The README says to use `environments/dev.env` but the `.gitignore` only ignores `environments/development.env`. This add's `dev.env` to the `.gitignore` for new users and leaves `development.env` ignored for anyone that still uses that file.
As seen here: https://github.com/canonical-websites/build.snapcraft.io/pull/1129#pullrequestreview-143883946

.gitignore environments/dev.env

---

src/common/actions/auth-store.js
src/common/components/session-overlay/index.js
test/unit/src/common/actions/t_auth-store.js

Fixes #1146
When session expires instead of signing out and reloading the page (which results in redirect and sign out from snapcraft.io) we now just clear the session and redirect to /auth/authenticate, to sign user back in (they are likely still signed it to their GH account anyway).
- Sign in (go to your repos page)
- Make your session expired ([make session shorter ](https://github.com/canonical-websites/build.snapcraft.io/blob/master/src/server/helpers/session.js#L11) or delete cookies)
- Click on 'Refresh the page' link on session expired warning
- You should be redirected back …

Redirect to login after session expired

---

src/common/components/footer/index.js

Updated footer to include `Charmed Distribution of Kubernetes` and 2019
- Check out this feature branch or open the demo service
- Check the footer has included information: `Charmed Distribution of Kubernetes` and 2019
Fixes #1187

Updated footer to include CDK and updated year

---

src/common/actions/auth-store.js
src/common/actions/register-name.js
src/common/helpers/launchpad.js
src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/actions/t_auth-store.js

We also set this in `authorizeSnap`, but setting it when we create the
snap in Launchpad makes some things a bit less confusing on the
Launchpad side: snaps created by build.snapcraft.io currently end up
sometimes being processed by an obsolete migration job to backfill
`store_series`, which is odd.

Set store series when creating a snap

---

src/common/helpers/launchpad.js
src/server/handlers/launchpad.js
test/routes/src/server/routes/t_launchpad.js
test/unit/src/common/helpers/t_snap-builds.js
test/unit/src/common/reducers/t_snap-builds.js
test/unit/src/common/reducers/t_snaps.js

Launchpad now supports inferring the correct series dynamically from
`snapcraft.yaml`.  By no longer hardcoding xenial, we gain `core18`
support.
We'll also need to remove the now-unnecessary `distro_series`
configuration from existing snaps, but I'll deal with that after this
has been deployed to production.
Fixes #1185.

Stop configuring new snaps to build on xenial

---

src/common/components/footer/index.js

Currently, there is no usage of CDK or Kubernetes at all in the process of build.snapcraft.io. Until further notice, we are removing the reference.
- Check the footer does not have any reference to CDK

Removed CDK reference from footer until further notice

---

npm-shrinkwrap.json
package.json
src/common/index.js
src/common/style/vanilla/css/footer.css
src/common/style/vanilla/css/navigation.css
src/common/style/vanilla/footer.scss
src/common/style/vanilla/navigation.scss
src/server/helpers/html.js
webpack/loaders-config.js

Adds Canonical global nav (and fixes related styling conflicts).
- Global nav should appear on top
- Open/close global nav 'Products' dropdown
- Navigate to different BSI pages, see if global nav works as expected
- Check if there are no styling issues, z-index problems, etc
Fixes #1183

Add global nav

---

src/common/index.js
webpack/loaders-config.js

#1202 added @canonical/global-nav as a dependency, but it was still imported as `global-nav` (without namespace) causing failures on clean deployments.
This PR fixes this by properly namespacing all occurrences of global-nav.
- `rm -rf node_modules`
- `npm install`
- Everything should build without errors, site with global nav should be displayed

Propely namespace all global-nav occurences

---

src/server/handlers/launchpad.js

Removes session requirement from `findSnap` handler to make builds and build pages are accessible by non signed-in users.
- Without signing in go directly to an existing repo or build page (/user/bartaz/example-repo /user/bartaz/example-repo/12345)
- Pages should load normally without 'Session expired' warning
- Sign in with GH account
- Go from 'My repos' to a repo or build page
- It should load normally
- Make your session expire (wait very long or remove session cookies)
- No warning should be shown, page should pool for build updates normally without any errors
- Go to 'My repos'
- …

Make builds pages public again

---

src/common/actions/register-name.js
src/common/components/repository-row/index.js
test/unit/src/common/actions/t_register-name.js

Makes sure unnecessary builds are not triggered after registering name:
- when builds are already in progress
- when name is mismatched (snapcraft.yaml name doesn't match registered name)
- Sign in and go to "My repos"
- Add a new repo (with snapcraft.yaml), register its name
- Builds should be triggered
- Go to builds list for this repository there should be only one build per architecture running (check latest and previous builds list as per #1205)
- Go back to My repos
- Change registered name of a snap to a name that doesn't match one from snapcraft.yaml
- "Name mismatch" should …

Fix unnecessary builds

---

src/common/components/footer/index.js
src/common/style/vanilla/css/footer.css
src/common/style/vanilla/css/grid.css
src/common/style/vanilla/footer.scss
src/common/style/vanilla/grid.scss

Fixes #1218 
Updates alignment of footer social icons.
Fixes width of `.row` to make build.snapcraft.io styles consistent with Vanilla 1.7.
- Look at the footer. Width of the footer should be consistent with page width. Social icons should be right aligned.

Fix footer social icons align

---

src/common/containers/build-details.js

Since Snapcraft 3.4 you will need to use a different syntax to
test builds comparable with how the build.snapcraft.io build
system does builds.
Fixes #1194
[List of work items including drive-bys]
- [List additional steps to QA the new features or prove the bug has been resolved]
[List of links to GitHub issues/bugs and cards if needed - e.g. `Fixes #1`]
[if relevant, include a screenshot]

Update "Debug this build" instructions

---

src/common/components/header/index.js

Adds IoT page to navigation for snapcraft.io consistency
- Check if navigation contains IoT page, verify link works

Add IoT to navigation

---

src/server/handlers/badge.js

Add extra cache prevention headers to the build badge response. This should help
reduce caching on GitHub README's.
I haven't tested it yet, but it is a very simple change.
Resolves #1248.

Add Extra Cache Headers To Build Badge Response

---

src/server/helpers/github.js
test/routes/src/server/routes/t_webhook.js

- According to an email GitHub will [stop supporting query parameter auth](https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters)
- Basic auth should be used instead
- [This page](https://developer.github.com/v3/apps/oauth_applications/#check-a-token) is a new endpoint that will check the validity of tokens - it says:
```
You must use Basic Authentication to use this endpoint, where the username is the OAuth application client_id and the password is its client_secret.
```
- I have implemented this and it seems to work locally
- View the site locally in your web browser at: …

Use basic auth for GitHub
